### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by IVData** [dlandon/zoneminder#1]
I've configured email in zoneminder following [this guide](https://wiki.zoneminder.com/How_to_get_ssmtp_working_with_Zoneminder) and it seems that email sending is not triggered by zoneminder at all. There's nothing in the logs or console output to say it's trying to send an email.

Could this possibly be an issue with the docker container? I have email set up the same on another non-docker install of zoneminder and it's working fine.

**Comment by dlandon** [comment]
I don't think so.  I added the specified modules from the guide.

In the guide is a script to test that email is working.  Did you try 
that?  You have to go into the docker to execute the command.  Be sure 
this works.

There are specific requirements set out in the guide for configuring 
email notifications.  Be sure to follow the instructions for 1.30 and 
later.

Dan Landon
Please note my new email address: dlandon@FamilyOfLandon.com



------ Original Message ------

**Comment by IVData** [comment]
Forgive me, I had not set up a filter for the emails to send (which should definitely be included in that guide). Issue resolved.
