### ISSUE TITLE
Problem with permissions added storage

### ISSUE THREAD

**Issue by RHCPNG** [dlandon/zoneminder#100]
I'm struggling with a permissions issue for added storage in my container. I have read every post on the topic, but can't get it to work.

I've added a bind volume to my container like this:

-v "/media/NAS_shared/Surveillance/zoneminder":"/nas":rw

I have tried all combinations of owners and permissions for dir /nas and underlying dirs:

zoneminder:www-data
www-data:www-data
root:www-data

In the end I set the permissions to 777 for the /nas directory

Zoneminder keeps giving me the following error:

"disk_total_space returned false for /nas"

Can somebody please tell me what the right procedure is of adding storage to the docker container?

ps. I use the default PUID 99 and PGID 100

**Comment by RHCPNG** [comment]
I also see the following error in the log: "can't mkdir /nas/1: Stale file handle"

**Comment by RHCPNG** [comment]
Ok, this is killing me. I started over at least 10 times with all possible permissions, nothing works. Every time I add the storage it gives me the "disk_total_space returned false for /nas" error and zoneminder can't create the "1" directory. 

I don't get it. I could try and mount the nfs share manually in the container, but that shouldn't be necessary.

Anybody any ideas?

**Comment by dlandon** [comment]
You should probably be looking at the host about file permissions.

**Comment by PrplHaz4** [comment]
I worked on a similar problem a couple days ago.  Here's what I did that seems to be working.

1. Create `userscript.sh` (that'll land in `/config` in the container) for the new storage location that looks exactly like the part of `init/40_firstrun.sh` script that sets up the event directories.  Replace `/var/cache/zoneminder2` with `/nas` (or whatever path you want to use as a new storage area in the container)
2. Make sure target directory (`/media/NAS_shared/Surveillance/zoneminder`) is empty - delete all subdirectories if needed
3. Start zoneminder container - watch logs for the new userscript being run
4. Configure the new storage location in zm web app

I had a lot of trouble finding what permissions were supposed to look like on the host, so I'll put mine here.  I think the key was allowing the container to create the subdirectories (events, images, temp, cache) and set permissions.

Host permissions
```bash
root@srv-host:~# ls -la /srv/dev-disk-by-label-storage3t02/zoneminder/
total 24
drwxr-xr-x 6 zoneminder users    4096 Jun 26 23:28 .
drwxr-xr-x 4 root       root     4096 Jun 26 15:28 ..
drwxrwxrwx 2 www-data   www-data 4096 Jun 26 23:28 cache
drwxrwxrwx 8 www-data   www-data 4096 Jun 28 14:32 events
drwxrwxrwx 2 www-data   www-data 4096 Jun 26 23:28 images
drwxrwxrwx 2 www-data   www-data 4096 Jun 26 23:28 temp
```
Docker permissions:
```
root@srv-dockerzm:/# ls -la /var/cache/zoneminder2/
total 28
drwxr-xr-x 6     1001 users    4096 Jun 26 23:28 .
drwxr-xr-x 1 root     root     4096 Jun 27 21:39 ..
drwxrwxrwx 2 www-data www-data 4096 Jun 26 23:28 cache
drwxrwxrwx 8 www-data www-data 4096 Jun 28 14:32 events
drwxrwxrwx 2 www-data www-data 4096 Jun 26 23:28 images
drwxrwxrwx 2 www-data www-data 4096 Jun 26 23:28 temp
```

from https://github.com/dlandon/zoneminder/blob/master/init/40_firstrun.sh#L213

`/config/userscript.sh` inside container
```
#### /var/cache/zoneminder2 ####
echo "userscript.sh: Check /var/cache/zoneminder2 subdirectories and permissions"
# Create events folder
if [ ! -d /var/cache/zoneminder2/events ]; then
	echo "Create events folder"
	mkdir /var/cache/zoneminder2/events
	chown -R www-data:www-data /var/cache/zoneminder2/events
	chmod -R 777 /var/cache/zoneminder2/events
else
	echo "Using existing data directory for events"

	# Check the ownership on the /var/cache/zoneminder2/events directory
	if [ `stat -c '%U:%G' /var/cache/zoneminder2/events` != 'www-data:www-data' ]; then
		echo "Correcting /var/cache/zoneminder2/events ownership..."
		chown -R www-data:www-data /var/cache/zoneminder2/events
	fi

	# Check the permissions on the /var/cache/zoneminder2/events directory
	if [ `stat -c '%a' /var/cache/zoneminder2/events` != '777' ]; then
		echo "Correcting /var/cache/zoneminder2/events permissions..."
		chmod -R 777 /var/cache/zoneminder2/events
	fi
fi

# Create images folder
if [ ! -d /var/cache/zoneminder2/images ]; then
	echo "Create images folder"
	mkdir /var/cache/zoneminder2/images
	chown -R www-data:www-data /var/cache/zoneminder2/images
	chmod -R 777 /var/cache/zoneminder2/images
else
	echo "Using existing data directory for images"

	# Check the ownership on the /var/cache/zoneminder2/images directory
	if [ `stat -c '%U:%G' /var/cache/zoneminder2/images` != 'www-data:www-data' ]; then
		echo "Correcting /var/cache/zoneminder2/images ownership..."
		chown -R www-data:www-data /var/cache/zoneminder2/images
	fi

	# Check the permissions on the /var/cache/zoneminder2/images directory
	if [ `stat -c '%a' /var/cache/zoneminder2/images` != '777' ]; then
		echo "Correcting /var/cache/zoneminder2/images permissions..."
		chmod -R 777 /var/cache/zoneminder2/images
	fi
fi

# Create temp folder
if [ ! -d /var/cache/zoneminder2/temp ]; then
	echo "Create temp folder"
	mkdir /var/cache/zoneminder2/temp
	chown -R www-data:www-data /var/cache/zoneminder2/temp
	chmod -R 777 /var/cache/zoneminder2/temp
else
	echo "Using existing data directory for temp"

	# Check the ownership on the /var/cache/zoneminder2/temp directory
	if [ `stat -c '%U:%G' /var/cache/zoneminder2/temp` != 'www-data:www-data' ]; then
		echo "Correcting /var/cache/zoneminder2/temp ownership..."
		chown -R www-data:www-data /var/cache/zoneminder2/temp
	fi

	# Check the permissions on the /var/cache/zoneminder2/temp directory
	if [ `stat -c '%a' /var/cache/zoneminder2/temp` != '777' ]; then
		echo "Correcting /var/cache/zoneminder2/temp permissions..."
		chmod -R 777 /var/cache/zoneminder2/temp
	fi
fi

# Create cache folder
if [ ! -d /var/cache/zoneminder2/cache ]; then
	echo "Create cache folder"
	mkdir /var/cache/zoneminder2/cache
	chown -R www-data:www-data /var/cache/zoneminder2/cache
	chmod -R 777 /var/cache/zoneminder2/cache
else
	echo "Using existing data directory for cache"

	# Check the ownership on the /var/cache/zoneminder2/cache directory
	if [ `stat -c '%U:%G' /var/cache/zoneminder2/cache` != 'www-data:www-data' ]; then
		echo "Correcting /var/cache/zoneminder2/cache ownership..."
		chown -R www-data:www-data /var/cache/zoneminder2/cache
	fi

	# Check the permissions on the /var/cache/zoneminder2/cache directory
	if [ `stat -c '%a' /var/cache/zoneminder2/cache` != '777' ]; then
		echo "Correcting /var/cache/zoneminder2/cache permissions..."
		chmod -R 777 /var/cache/zoneminder2/cache
	fi
fi
```

**Comment by RHCPNG** [comment]
> You should probably be looking at the host about file permissions.

I have tried setting the permissions on the host, it doesn’t make a difference, it seems.

**Comment by RHCPNG** [comment]
> I worked on a similar problem a couple days ago. Here's what I did that seems to be working.
> 
> 1. Create `userscript.sh` (that'll land in `/config` in the container) for the new storage location that looks exactly like the part of `init/40_firstrun.sh` script that sets up the event directories.  Replace `/var/cache/zoneminder2` with `/nas` (or whatever path you want to use as a new storage area in the container)
> 2. Make sure target directory (`/media/NAS_shared/Surveillance/zoneminder`) is empty - delete all subdirectories if needed
> 3. Start zoneminder container - watch logs for the new userscript being run
> 4. Configure the new storage location in zm web app
> 
> I had a lot of trouble finding what permissions were supposed to look like on the host, so I'll put mine here. I think the key was allowing the container to create the subdirectories (events, images, temp, cache) and set permissions.
> 
> Host permissions
> 
> ```shell
> root@srv-host:~# ls -la /srv/dev-disk-by-label-storage3t02/zoneminder/
> total 24
> drwxr-xr-x 6 zoneminder users    4096 Jun 26 23:28 .
> drwxr-xr-x 4 root       root     4096 Jun 26 15:28 ..
> drwxrwxrwx 2 www-data   www-data 4096 Jun 26 23:28 cache
> drwxrwxrwx 8 www-data   www-data 4096 Jun 28 14:32 events
> drwxrwxrwx 2 www-data   www-data 4096 Jun 26 23:28 images
> drwxrwxrwx 2 www-data   www-data 4096 Jun 26 23:28 temp
> ```
> 
> Docker permissions:
> 
> ```
> root@srv-dockerzm:/# ls -la /var/cache/zoneminder2/
> total 28
> drwxr-xr-x 6     1001 users    4096 Jun 26 23:28 .
> drwxr-xr-x 1 root     root     4096 Jun 27 21:39 ..
> drwxrwxrwx 2 www-data www-data 4096 Jun 26 23:28 cache
> drwxrwxrwx 8 www-data www-data 4096 Jun 28 14:32 events
> drwxrwxrwx 2 www-data www-data 4096 Jun 26 23:28 images
> drwxrwxrwx 2 www-data www-data 4096 Jun 26 23:28 temp
> ```
> 
> from https://github.com/dlandon/zoneminder/blob/master/init/40_firstrun.sh#L213
> 
> `/config/userscript.sh` inside container
> 
> ```
> #### /var/cache/zoneminder2 ####
> echo "userscript.sh: Check /var/cache/zoneminder2 subdirectories and permissions"
> # Create events folder
> if [ ! -d /var/cache/zoneminder2/events ]; then
> 	echo "Create events folder"
> 	mkdir /var/cache/zoneminder2/events
> 	chown -R www-data:www-data /var/cache/zoneminder2/events
> 	chmod -R 777 /var/cache/zoneminder2/events
> else
> 	echo "Using existing data directory for events"
> 
> 	# Check the ownership on the /var/cache/zoneminder2/events directory
> 	if [ `stat -c '%U:%G' /var/cache/zoneminder2/events` != 'www-data:www-data' ]; then
> 		echo "Correcting /var/cache/zoneminder2/events ownership..."
> 		chown -R www-data:www-data /var/cache/zoneminder2/events
> 	fi
> 
> 	# Check the permissions on the /var/cache/zoneminder2/events directory
> 	if [ `stat -c '%a' /var/cache/zoneminder2/events` != '777' ]; then
> 		echo "Correcting /var/cache/zoneminder2/events permissions..."
> 		chmod -R 777 /var/cache/zoneminder2/events
> 	fi
> fi
> 
> # Create images folder
> if [ ! -d /var/cache/zoneminder2/images ]; then
> 	echo "Create images folder"
> 	mkdir /var/cache/zoneminder2/images
> 	chown -R www-data:www-data /var/cache/zoneminder2/images
> 	chmod -R 777 /var/cache/zoneminder2/images
> else
> 	echo "Using existing data directory for images"
> 
> 	# Check the ownership on the /var/cache/zoneminder2/images directory
> 	if [ `stat -c '%U:%G' /var/cache/zoneminder2/images` != 'www-data:www-data' ]; then
> 		echo "Correcting /var/cache/zoneminder2/images ownership..."
> 		chown -R www-data:www-data /var/cache/zoneminder2/images
> 	fi
> 
> 	# Check the permissions on the /var/cache/zoneminder2/images directory
> 	if [ `stat -c '%a' /var/cache/zoneminder2/images` != '777' ]; then
> 		echo "Correcting /var/cache/zoneminder2/images permissions..."
> 		chmod -R 777 /var/cache/zoneminder2/images
> 	fi
> fi
> 
> # Create temp folder
> if [ ! -d /var/cache/zoneminder2/temp ]; then
> 	echo "Create temp folder"
> 	mkdir /var/cache/zoneminder2/temp
> 	chown -R www-data:www-data /var/cache/zoneminder2/temp
> 	chmod -R 777 /var/cache/zoneminder2/temp
> else
> 	echo "Using existing data directory for temp"
> 
> 	# Check the ownership on the /var/cache/zoneminder2/temp directory
> 	if [ `stat -c '%U:%G' /var/cache/zoneminder2/temp` != 'www-data:www-data' ]; then
> 		echo "Correcting /var/cache/zoneminder2/temp ownership..."
> 		chown -R www-data:www-data /var/cache/zoneminder2/temp
> 	fi
> 
> 	# Check the permissions on the /var/cache/zoneminder2/temp directory
> 	if [ `stat -c '%a' /var/cache/zoneminder2/temp` != '777' ]; then
> 		echo "Correcting /var/cache/zoneminder2/temp permissions..."
> 		chmod -R 777 /var/cache/zoneminder2/temp
> 	fi
> fi
> 
> # Create cache folder
> if [ ! -d /var/cache/zoneminder2/cache ]; then
> 	echo "Create cache folder"
> 	mkdir /var/cache/zoneminder2/cache
> 	chown -R www-data:www-data /var/cache/zoneminder2/cache
> 	chmod -R 777 /var/cache/zoneminder2/cache
> else
> 	echo "Using existing data directory for cache"
> 
> 	# Check the ownership on the /var/cache/zoneminder2/cache directory
> 	if [ `stat -c '%U:%G' /var/cache/zoneminder2/cache` != 'www-data:www-data' ]; then
> 		echo "Correcting /var/cache/zoneminder2/cache ownership..."
> 		chown -R www-data:www-data /var/cache/zoneminder2/cache
> 	fi
> 
> 	# Check the permissions on the /var/cache/zoneminder2/cache directory
> 	if [ `stat -c '%a' /var/cache/zoneminder2/cache` != '777' ]; then
> 		echo "Correcting /var/cache/zoneminder2/cache permissions..."
> 		chmod -R 777 /var/cache/zoneminder2/cache
> 	fi
> fi
> ```

Thanks for the suggestion, I will try this.

**Comment by RHCPNG** [comment]
Creating the directories with the userscript doens't work for me. The directories are created succesfully, but the error remains. Zoneminder can't write to the directory somehow.

@dlandon Do you have any ideas? This is very strange.

Permissions in docker:
root@7385a7213c31:/nas# ls -la
total 24
drwxrwxrwx 2 nobody   users    4096 Jul  4 09:19 .
drwxr-xr-x 1 root     root     4096 Jul  4 09:56 ..
drwxrwxrwx 2 www-data www-data 4096 Jul  4 09:56 cache
drwxrwxrwx 2 www-data www-data 4096 Jul  4 09:56 events
drwxrwxrwx 2 www-data www-data 4096 Jul  4 09:56 images
drwxrwxrwx 2 www-data www-data 4096 Jul  4 09:56 temp

Permissions on host:
niels@OMV:/$ ls -la /srv/pool/media/videos/Surveillance/zoneminder
total 24
drwxrwxrwx 2 zoneminder users    4096 Jul  4 09:19 .
drwxr-xr-x 3 root       users    4096 Jun 28 09:16 ..
drwxrwxrwx 2 www-data   www-data 4096 Jul  4 09:56 cache
drwxrwxrwx 2 www-data   www-data 4096 Jul  4 09:56 events
drwxrwxrwx 2 www-data   www-data 4096 Jul  4 09:56 images
drwxrwxrwx 2 www-data   www-data 4096 Jul  4 09:56 temp

**Comment by dlandon** [comment]
Are you starting the Docker priviledged?

**Comment by RHCPNG** [comment]
> Are you starting the Docker priviledged?

Yes

**Comment by dlandon** [comment]
Try not privileged.

**Comment by RHCPNG** [comment]
Doesn't make a difference, same errors (and a lot more :-) )

**Comment by RHCPNG** [comment]
When I log into the container with www-data, I get the following:

bash: /root/.bashrc: Permission denied
www-data@7385a7213c31:/$ cd /nas
bash: cd: /nas: Stale file handle

So apparently www-data doesn't have the right permissions, but I don't know why yet.

**Comment by RHCPNG** [comment]
I'm one step closer. I have set the the option "no_subtree_check" on my nfs share and now I don't get the error "disk_total_space returned false for /nas" anymore and is the percentage for the disk space availability shown correctly.

But I still get the error "Can't mkdir /nas/1: No such file or directory".

When I log in to the container with www-data, now I get this:

www-data@7385a7213c31:/$ cd /nas
bash: cd: /nas: No such file or directory

**Comment by RHCPNG** [comment]
Still no luck. There seems to be a problem with www-data in the docker or something. I can't get it to access the /nas mount.

I use the exact same setup in other dockers and have used it in zoneminder docker in the past succesfully too.

**Comment by RHCPNG** [comment]
Anyone has any more ideas? I have tried to mount a different nfs location to the host and use that as volume in the docker, but to no succes.

It keeps saying the path does not exist, although I see the directory and subdirectories when I connect to the docker with root. www-data has all permissions so I don't understand why zoneminder can't access the directory.

**Comment by PrplHaz4** [comment]
Can you write to the directory as root on host and in docker?

It looks like you can since all of the proper subdirs were created - you should probably kill those subdirs between tries to make sure you're working with fresh permissions when the container is started.

**Comment by RHCPNG** [comment]
Yes, I can write to the directory from host and docker.

I'm one step closer to the root cause, but I could use some more help.

I have mounted 2 bind volumes to the docker, both are nfs shares on the host. The nfs shares come from different hosts and one is working in the docker and the other is not. So the one that isn't working is the problem of this thread.

I have compared the two and I see few differences, maybe you guys have some thoughts.

/etc/export of the nfs that's NOT working:
```
# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

# /etc/exports: the access control list for filesystems which may be exported
#               to NFS clients.  See exports(5).
/export/shared 192.168.1.0/24(fsid=1,rw,no_subtree_check,insecure,no_root_squash)
/export/zoneminder 192.168.1.0/24(fsid=2,rw,no_subtree_check,insecure,no_root_squash)

# NFSv4 - pseudo filesystem root
/export 192.168.1.0/24(ro,fsid=0,root_squash,no_subtree_check,hide)
```

/etc/export of the working nfs share:
```
# /etc/exports: the access control list for filesystems which may be exported
#               to NFS clients.  See exports(5).
#
# Example for NFSv2 and NFSv3:
# /srv/homes       hostname1(rw,sync,no_subtree_check) hostname2(ro,sync,no_subtree_check)
#
# Example for NFSv4:
# /srv/nfs4        gss/krb5i(rw,sync,fsid=0,crossmnt,no_subtree_check)
# /srv/nfs4/homes  gss/krb5i(rw,sync,no_subtree_check)
#
/mnt/vmdataExt/dockers 192.168.1.0/24(rw,no_root_squash,sync,no_subtree_check)
```
Fstab file on the host:
```
# /etc/fstab: static file system information.
#
# Use 'blkid' to print the universally unique identifier for a
# device; this may be used with UUID= as a more robust way to name devices
# that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
# / was on /dev/sda2 during curtin installation
/dev/disk/by-uuid/90fbdb92-a7c6-4290-afc7-36ec30887211 / ext4 defaults 0 0
/swap.img       none    swap    sw      0       0
192.168.1.10:/mnt/vmdataExt/dockers     /media/dockers  nfs4    defaults,user,exec      0 0    ---> working nfs
192.168.1.100:/shared           /media/NAS_shared       nfs4    defaults,user,exec 0 0              ---> NOT working
192.168.1.100:/zoneminder       /media/zoneminder       nfs4    defaults,user,exec 0 0            ---> NOT working
```
The difference I see of course is the root file system of nfs4 in the non-working nfs, but I can't change that (is controlled by OMV) and that's actually the right way to do it.

The strange thing is that NFS share seems to be working fine on other docker containers.

Anyone has any ideas on how to proceed?

**Comment by RHCPNG** [comment]
ok, I've got a workaround for this issue. But I don't understand why this works yet. 

The mount works if I use the following options for my nfs:
no_subtree_check,insecure,**all_squash,anonuid=99,anongid=100**

The last two options make the difference. When I use "no_root_squash" it stops working.

 Maybe someone can explain why this works and the other options doesn't? Does this is because zoneminder works under the anon user?
