### ISSUE TITLE
Can not add camera accessible over VPN network

### ISSUE THREAD

**Issue by reschandreas** [dlandon/zoneminder#101]
I configured Zoneminder on my server outside of my local network and connected it via OpenVPN hosted on a Raspberry PI at home to my local network. The camera is pingable and responding just fine wia curl so a connection is definitely there. However the camera is not detected when added to a monitor inside Zoneminder. Is there a restriction which network interface is scanned for cameras in Zoneminder?
Sorry if this is a very basic issue, I'm still new to Zoneminder.
Thanks!

**Comment by connortechnology** [comment]
ONVIF probe only scans the network with the default route.  So it is likely not scanning your vpn link. This has been improved in 1.35.

**Comment by reschandreas** [comment]
Good to know. But my problem also persists when simply adding the camera as a source for my monitor as shown in this
![image](https://user-images.githubusercontent.com/16179620/86148200-9dc8e300-bafa-11ea-943e-b876f59a4f1d.png)
The camera answers on that IP but the monitor does not work.

**Comment by rchovan** [comment]
I have similar problem, try to add as local ffmpeg with source rtsp://192.168.1.33:554/11 and see what is in logs.

**Comment by dlandon** [comment]
Please go to the Zoneminder forum for support.
