### ISSUE TITLE
Can't open memory map file /dev/shm/zm.mmap.1, probably not enough space free: Permission denied

### ISSUE THREAD

**Issue by kiwijunglist** [dlandon/zoneminder#103]
Hi

Thanks for creating this docker for zoneminder.

I can't seem to get this container working.  All my other containers are working fine and have same permissions in both the compose file and also the directories that the other containers write to.  When I try to add a camera and set to monitor I get this error.

Can't open memory map file /dev/shm/zm.mmap.1, probably not enough space free: Permission denied
Memory map file '/dev/shm/zm.mmap.1' does not exist in zmMemAttach. zmc might not be running.

Can I please get some help, really keen to get this going, Thanks.

**Comment by kiwijunglist** [comment]
As I test I can run a console inside the docker container, and I have no permissions issue when I try to access the storage volumes or create test files etc from a console inside the docker container.

**Comment by kiwijunglist** [comment]
Error Log:
```
2020-07-04 21:14:30 | zmc_m2 |   | 987 | ERR | Can't mkdir /datanvr/2: Permission denied
```

Proof that the container has access to mkdir
```
mike@server:~$ docker exec -it zoneminder /bin/bash
root@f1c478a7d0c1:/# cd /datanvr
root@f1c478a7d0c1:/datanvr# whoami
root
root@f1c478a7d0c1:/datanvr# mkdir testtest
root@f1c478a7d0c1:/datanvr# mkdir 2
root@f1c478a7d0c1:/datanvr# ls
2  test  testtest
root@f1c478a7d0c1:/datanvr#
```

**Comment by kiwijunglist** [comment]
Stats:
```
trending_up Load: 0.86 storage DB:7/151 Storage: NewStorage: 65% , nasdvr: 65% /dev/shm: 0%
```

**Comment by connortechnology** [comment]
That's not proof.  You are acting as root.  ZM runs as www-data or some other user.
ls -l /datanvr will likely show that it is NOT owned by www-data.

**Comment by connortechnology** [comment]
Also give us a df /dev/shm

**Comment by jackbradach** [comment]
I just ran into this message as well.  Root cause for me was that I'd split the envvars out of the docker-compose.yml and when I did so, I wrote SHMEM="50%" rather than SHMEM=50%.  Part of the startup scripts unmount/remounts /dev/shm using that envvar as the size parameter.  With the quotes, the mount command fails and zmc can't attach to anything.

**Comment by kiwijunglist** [comment]
> I just ran into this message as well. Root cause for me was that I'd split the envvars out of the docker-compose.yml and when I did so, I wrote SHMEM="50%" rather than SHMEM=50%. Part of the startup scripts unmount/remounts /dev/shm using that envvar as the size parameter. With the quotes, the mount command fails and zmc can't attach to anything.

this was my problem as well.

**Comment by kiwijunglist** [comment]
> Also give us a df /dev/shm

thank you for your help it was SHMEM="50%" rather than SHMEM=50% in the compose file.
