### ISSUE TITLE
zoneminder can't autostart

### ISSUE THREAD

**Issue by adamf663** [dlandon/zoneminder#104]
If I set docker's start (at boot) flag for zoneminder, the monitors never initialize and have a constant stream of the following two errors:
Failed to prime capture of initial monitor
Unable to open input rtsp://<userid:passwd>@<camera>:8554/unicast due to: Input/output error
If I issue a docker restart Zoneminder, it starts normally.

**Comment by dlandon** [comment]
What is the host system?  I would say that the Docker is starting too early in the boot up process.  Is there a way to delay the ZM Docker start?

**Comment by adamf663** [comment]
it is hosted on ubuntu server, version 20.4.  The docker version is:
  docker.io      19.03.8-0ubuntu1.20.04 amd64

The systemd service file seems to have it waiting for containerd and network-online.target.
Containerd requires the network and local-fs targets.

**Comment by dlandon** [comment]
Can you add a delay to give the network and local fs time to be up and running?  Do you see anything in the logs that would indicate why the ZM Docker is not starting?

**Comment by adamf663** [comment]
I'll try that -- I'm still learning about docker's internals.

**Comment by adamf663** [comment]
I ended up adding the following to the systemd service file /lib/systemd/system/docker.service:
ExecStartPre=/bin/sleep 60

zoneminder is working without being restarted.
