### ISSUE TITLE
Cant find Yolo or hook files inside the container.

### ISSUE THREAD

**Issue by neophitus** [dlandon/zoneminder#109]
After a 

docker run -d --name="Zoneminder" --restart=always --net="bridge" --privileged="true" -p 7443:443/tcp -p 9000:9000/tcp -e TZ="America/Sao_Paulo" -e SHMEM="50%" -e PUID="99" -e PGID="100" -e INSTALL_HOOK=“1” -e INSTALL_FACE=“1” -e INSTALL_TINY_YOLO=“1” -e INSTALL_YOLO=“0” -e MULTI_PORT_START="0" -e MULTI_PORT_END="0" -v "/mnt/storage/Zoneminder":"/config":rw -v "/mnt/storage/Zoneminder/data":"/var/cache/zoneminder":rw dlandon/zoneminder

i chat find yolo files or even the hook scripts inside the container. Ani tips?

**Comment by joselito11** [comment]
/var/lib/zmeventnotification/models/

**Comment by neophitus** [comment]
> In container /var/lib/zmeventnotification/models/

No. Its not. For some reason the files was not downloaded.

**Comment by dlandon** [comment]
Look at the log and see what didn't work.

**Comment by ancker010** [comment]
Seeing similar issue. Used:

**Comment by ancker010** [comment]
> Seeing similar issue. Used:
> 
> `-e INSTALL_TINY_YOLOV4=“1” -e INSTALL_YOLOV4=“1”`
> 
> Models not found in the hooks/models directory.
> Looked through the docker logs for any errors and there was nothing there.

I may have fixed my own issue. Needed to `docker rmi <image>` a stale version of the container. `docker run` wasn't pulling the latest for some reason...

**Comment by ancker010** [comment]
> > Seeing similar issue. Used:
> > `-e INSTALL_TINY_YOLOV4=“1” -e INSTALL_YOLOV4=“1”`
> > Models not found in the hooks/models directory.
> > Looked through the docker logs for any errors and there was nothing there.
> 
> I may have fixed my own issue. Needed to `docker rmi <image>` a stale version of the container. `docker run` wasn't pulling the latest for some reason...

I take that back, didn't help. I did the download manually for the yolov4 files but something still isn't right. The eventnotificationserver is working, but fails for some reason.

`Sep  7 18:36:23 27646897a30e zmeventnotification[19507]: INF [|----> FORK:KitchenCam (6), eid:474656 Event 474656 for Monitor 6 has finished]
`
`Sep  7 18:36:27 27646897a30e zmeventnotification[19507]: INF [|----> FORK:KitchenCam (6), eid:474656 Not sending event end alarm, as we did not send a start alarm for this, or start hook processing failed]`

**Comment by dlandon** [comment]
The yolo files are at /config/hook/models/.  Inside the container at /var/lib/zmeventnotification/models.  Use the environment variables to download the model files.
