### ISSUE TITLE
Connection to SQL DB error

### ISSUE THREAD

**Issue by jkvalence** [dlandon/zoneminder#11]
Good morning,

Transitioning from quantomobject zoneminder to yours since I need a simpler setup (they are moving towards swarm) and I have a single machine.  Anyways, got the following error when trying to launch the container.

Unable to connect to ZM db.SQLSTATE[HY000] [2002] Connection refused

A couple seconds after this appears in the browser, the container stops until I restart it.

**Comment by dlandon** [comment]
Check your database credentials.
