### ISSUE TITLE
Permission error and possible updates to script

### ISSUE THREAD

**Issue by peste85** [dlandon/zoneminder#114]
I tried running the docker and encountered some issues, I was able to fix them but i though i should let you know in case you want to update the script.

Script name 40_firstrun.sh

- line 378, you have the following
`wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names -O /config/hook/models/tinyyolov3/yolov3-tiny.txt`

it should be

`wget https://raw.githubusercontent.com/pjreddie/darknet/master/data/coco.names -O /config/hook/models/tinyyolov3/coco.names`

-line 488
you should probably also create the directory for the unknown_faces

`mkdir -p /config/hook/known_face`

After doing those, I am trying to train the faces for face recognition however I am getting a permission error, not sure if this is related to the docker or zm event, any ideas?

`PermissionError: [Errno 13] Permission denied: '/var/lib/zmeventnotification/known_faces/faces.dat'`

**Comment by dlandon** [comment]
This has been fixed.
