### ISSUE TITLE
Remove docker --privileged flag & replace by --shm-size="..."

### ISSUE THREAD

**Issue by TechNovation01** [dlandon/zoneminder#119]
Currently the docker-run.sh sets the `--privileged` flag, which is generally considered to be a something you seldomly want to do **(security issue)**. 
I looked a little into it why it was actually needed for this container and currently I believe it is there to enable the fix for the shared memory (SHMEM setting)  to go beyond the default 64MB docker limit.

If this is truly the reason I would propose to update the docker-run.sh by:

1. removing the `--privileged` & `-e SHMEM`
2. add the line `--shm-size="[size]"`, with [size] being your preferred amount in format according https://docs.docker.com/engine/reference/run/ (e.g. `--shm-size="2g"`).

I think this could prevent some of the prior issues (#106, #94), and reduce the related security risk.

**Comment by dlandon** [comment]
I don't believe this applies in all cases.  In my case running on Unraid, the the docker won't work properly without running privileged.

**Comment by subdavis** [comment]
> I don't believe this applies in all cases. In my case running on Unraid, the the docker won't work properly without running privileged

Could you explain why?  I was a little disappointed to see `--privileged` in your run example without explanation.  Any situation where this option is necessary requires a bit of investigation.

Thanks for maintaining this image.  I think most reasonable users would also appreciate a section of the README explaining this need.
