### ISSUE TITLE
Feature Request: Using an external MySQL DB

### ISSUE THREAD

**Issue by egadgetjnr** [dlandon/zoneminder#12]
Hey,
First of all, thank you so much for this. Your dockerfile works a treat.

Just a quick Question, would it be possible to somehow use an external MySQL DB server? 
I already have one running on my UnRaid box and didn't want to double up on it. Is this at all possible? Maybe through use of Environment Vars?

Thanks heaps!

**Comment by dlandon** [comment]
Read the first post of the Zoneminder thread in the unRAID forums.  It explains how to change databases.

**Comment by Germs2004** [comment]
Wouldn't the best solution be the one the other ZoneMinder docker images are using - environment variables?  I looked at an unRAID forum thread about this and it looks like they recommend modifying a file to point zm to the external mysql container, but it doesn't seem to have an easy way to prevent this container from installing the unwanted mysql application.  Ideally, the mysql application shouldn't be installed at all in this container.
```
-e ZM_DB_HOST=mydbserver \
-e ZM_DB_NAME=zm \
-e ZM_DB_USER=zmuser \
-e ZM_DB_PASS=mypass123 \
-e ZM_DB_PORT=3306 \
```

It looks like this docker image can't be easily made to do that but I hope you'll consider moving the db out of this container.

**Comment by dlandon** [comment]
This isn't something I will consider.  If I move the db out of the Docker, everyone using the Docker will have to reconfigure their setup and that will generate a lot of unwanted support for me - I don't get paid for this.   Changing the file to setup an external db is the way Zoneminder does it and I don't consider that a problem.  I don't understand why it's ideal to remove the db from the Docker when many users (including myself) prefer it that way.
