### ISSUE TITLE
opencv-contrib-python still downloading 4.2

### ISSUE THREAD

**Issue by cliffjao** [dlandon/zoneminder#120]
OpenCV is still downloading 4.2, which doesn't seem to work with YoloV4.

From logs:
> Collecting opencv-contrib-python
>   Downloading https://files.pythonhosted.org/packages/c6/db/790dbc6bcfea87fc6f790c6306509c2691ce31c96d82e5b826545d90ea52/opencv_contrib_python-4.2.0.34-cp36-cp36m-manylinux1_x86_64.whl (34.2MB)
> Requirement already satisfied: numpy>=1.11.3 in /usr/local/lib/python3.6/dist-packages (from opencv-contrib-python)
> Installing collected packages: opencv-contrib-python
> Successfully installed opencv-contrib-python-4.2.0.34

**Comment by dlandon** [comment]
That's what is installed from the Ubuntu repository.
