### ISSUE TITLE
Unrecoverable error:module 'pyzm.ZMLog' has no attribute 'error' 

### ISSUE THREAD

**Issue by DennisFaucher** [dlandon/zoneminder#121]
Hi. I wanted to add machine learning to the Zoneminder container. The Event Server in the container image works great but does not have the ML pieces. I git cloned the event server into a new directory and ran install.sh. That completed successfully. I restarted ZM but am getting this error in the Log:

Unrecoverable error:module 'pyzm.ZMLog' has no attribute 'error' Traceback:Traceback (most recent call last): File "/var/lib/zmeventnotification/bin/zmes_hook_helpers/utils.py", line 290, in process_config g.logger.debug('secret filename: {}'.format(secrets_filename))AttributeError: module 'pyzm.ZMLog' has no attribute 'debug'During handling of the above exception, another exception occurred:Traceback (most recent call last): File "/var/lib/zmeventnotification/bin/zm_detect.py", line 849, in <module> main_handler() File "/var/lib/zmeventnotification/bin/zm_detect.py", line 214, in main_handler utils.process_config(args, g.ctx) File "/var/lib/zmeventnotification/bin/zmes_hook_helpers/utils.py", line 354, in process_config g.logger.error('Error parsing config:{}'.format(args.get('config')))AttributeError: module 'pyzm.ZMLog' has no attribute 'error'

Ideas? TIA.

**Comment by dlandon** [comment]
Use the environment variables to install the hook processing.  You installed it manually; you're on your own.

**Comment by DennisFaucher** [comment]
Oh, excellent. Thank you. I did not realize that the container image had options for ML. I'll try starting the container with the ML options.

**Comment by DennisFaucher** [comment]
Removed the container and recreated with the YOLO and HOOK options, but still getting errors.

Container Run Command:

sudo docker run -d --name="Zoneminder" \
--net="bridge" \
--privileged="true" \
-p 8443:443/tcp \
-p 9000:9000/tcp \
-e TZ="America/New_York" \
-e SHMEM="50%" \
-e PUID="99" \
-e PGID="100" \
-e INSTALL_HOOK="1" \
-e INSTALL_FACE="0" \
-e INSTALL_TINY_YOLOV3="1" \
-e INSTALL_YOLOV3="0" \
-e INSTALL_TINY_YOLOV4="1" \
-e INSTALL_YOLOV4="0" \
-e MULTI_PORT_START="0" \
-e MULTI_PORT_END="0" \
-v "/Users/faucherd/Downloads/Zoneminder":"/config":rw \
-v "/Users/faucherd/Downloads/Zoneminder/data":"/var/cache/zoneminder":rw \
dlandon/zoneminder

Test command:  sudo -u www-data /var/lib/zmeventnotification/bin/zm_event_start.sh 1 1

Log:

error: Traceback:Traceback (most recent call last): File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open encode_chunked=req.has_header('Transfer-encoding')) File "/usr/lib/python3.6/http/client.py", line 1264, in request self._send_request(method, url, body, headers, encode_chunked) File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request self.endheaders(body, encode_chunked=encode_chunked) File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders self._send_output(message_body, encode_chunked=encode_chunked) File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output self.send(msg) File "/usr/lib/python3.6/http/client.py", line 976, in send self.connect() File "/usr/lib/python3.6/http/client.py", line 1417, in connect super().connect() File "/usr/lib/python3.6/http/client.py", line 948, in connect (self.host,self.port), self.timeout, self.source_address) File "/usr/lib/python3.6/socket.py", line 704, in create_connection for res in getaddrinfo(host, port, 0, SOCK_STREAM): File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo for res in _socket.getaddrinfo(host, port, family, type, proto, flags):socket.gaierror: [Errno -2] Name or service not knownDuring handling of the above exception, another exception occurred:Traceback (most recent call last): File "/var/lib/zmeventnotification/bin/zm_detect.py", line 222, in <module> args) File "/usr/local/lib/python3.6/dist-packages/zmes_hook_helpers/utils.py", line 168, in download_files input_file = opener.open(url) File "/usr/lib/python3.6/urllib/request.py", line 526, in open response = self._open(req, data) File "/usr/lib/python3.6/urllib/request.py", line 544, in _open '_open', req) File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain result = func(*args) File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open context=self._context, check_hostname=self._check_hostname) File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open raise URLError(err)urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by dlandon** [comment]
Try to get support for this on the Zoneminder forum.
