### ISSUE TITLE
zmNinja Login Fail

### ISSUE THREAD

**Issue by lee3521** [dlandon/zoneminder#123]
I am new to Zoneminder and docker.  I have zoneminder up and running with a few cameras.  When I try to use the zmNinja mobile app, I am getting the error': "API Access Failed". I am posting here because I suspect it has something to do with me running ZM as a docker container.  Can someone clue me in as to how to begin troubleshooting this?

**Comment by dlandon** [comment]
Ask for help on the Zoneminder support forum.
