### ISSUE TITLE
Event server not supported after zmninja upgrade

### ISSUE THREAD

**Issue by joselito11** [dlandon/zoneminder#124]
`Event server version not supported. You are running version version 5.15.6-Docker. Please upgrade to version 6.` 
This is error when I open the updated ZmNinja app v1.6001 on ios devices. ZM version is 1.34.21

**Comment by gfro84** [comment]
Yes please, an update to ES version 6 would be appreciated though I'd imagine as it incorporates breaking changes might take a while. 

I've become so lazy since finding this docker image, not having to regularly troubleshoot you forget where everything is!

Many thanks
George

**Comment by mobilizesoftware** [comment]
> `Event server version not supported. You are running version version 5.15.6-Docker. Please upgrade to version 6.`
> This is error when I open the updated ZmNinja app v1.6001 on ios devices. ZM version is 1.34.21

Confirming the same here with my installation

**Comment by danielme85** [comment]
Update plz 🙏

**Comment by ptruman** [comment]
Ditto on the error.  I upgraded handset and thought that was it :(

**Comment by keaves** [comment]
Same issue here. I've been loving this docker image for over a year now. Also got caught out by the zmninja update. Would be amazing if the ES could be updated. 
Thanks!

**Comment by ptruman** [comment]
See my post above - temp fix for me, although I don't have any changes in zmeventnotification.ini :)

**Comment by keaves** [comment]
I apologise @dlandon. His zonemaster master repo has been updated with ES 6. See here, https://github.com/dlandon/zoneminder.master-docker
I did a: docker pull dlandon/zoneminder.master  -After the upgrade ES 6 runs and zmninja is getting event notifications again
It does upgrade the zm database, and looks like there are noteworthy breaking changes to some configs. See here, https://github.com/dlandon/zoneminder.master-docker/issues/6#issuecomment-710012454
So backup AppData first

**Comment by dlandon** [comment]
Once I get feedback that everything is ok from the master docker, I'll publish it to the stable docker here.

There seems to be a configuration update script that needs to be executed.  I'll work on that later today.

Please post master related issues to the master Github.  Posting here is confusing the issue.  I know everyone is anxious to see the upgrade to ES 6, but I want to sort it out with the master docker so there is minimal impact on the stable docker.

**Comment by ptruman** [comment]
I've moved to Master.
ZMNinja is showing everything, but notifications aren't firing, and hooks aren't being called (even with a modded objectconfig.ini).

The main UI also seems a bit wonky with some empty tick boxes

![image](https://user-images.githubusercontent.com/1991779/96276073-72470700-0fca-11eb-9342-8453d2dd3a5e.png)

and the events "Showing 10" items dropdown won't let me change away from 10 :)
(functionally it's doing what ZM should, modect is running)

I'm off to dig logs :O)

**Comment by ptruman** [comment]
So, to update - I'm not getting events to fire (although it looks like I can see stuff in logs) and it doesn't look like the object detection is being called.

I've updated the container ENVs so I have:

INSTALL_HOOK | 1
INSTALL_FACE | 1
ZM_VERS | 1.34 (this appears to have not updated)
INSTALL_TINY_YOLO | 1
INSTALL_YOLO | 1

I'm getting

Monitor shm is not connected

And no obvious calls to hook (modect working) - but no obj dect or event notification

**Comment by dlandon** [comment]
Take your feedback to the master zoneminder issue so I can track it there.

I don't need anyone else telling me that ES 5 is breaking ZmNinja,  I'm working on it in the master docker because those users are more tolerant to problems.  You will just have to wat until we get through testing.  I don't use hook processing so I can't very easily test.

**Comment by ptruman** [comment]
Happy to assist testing either way

**Comment by pliablepixels** [comment]
My apologies to everyone here and dlandon too -> I should have explicitly mentioned I am going to make a significantly breaking update to dlandon. I've been posting about it on medium/ZM forums for about 2 months, but I know a lot of people don't follow those. I'll do a better job next time.

**Comment by dlandon** [comment]
The docker has been updated to ES 6.0.4.

The Event Server version 6 has implemented many changes to the objectconfig.ini of the hook processing.  Upgrading the docker will fix the ZmNinja version incompatibility problem, but the hook processing will not work until you update the objectconfig.ini file.

There are two ways to do this.

The easiest way is to get into the docker command line and do the following commands:
- cd /config/hook
- ./config_upgrade.sh

You will see a message about new configuration parameters and ones that can be removed.  You will need to edit the file and make adjustments for your particular needs.

The second method is to copy the objectconfig.ini.default script to objectconfig.ini and then edit the script for your particular needs.

**Comment by gfro84** [comment]
Thanks @dlandon for implementing this so quickly, your work is much appreciated.

**Comment by cliffjao** [comment]
@dlandon Is it possible to pull in the latest 6.0.5? There have been some fixes that I'd like to get in my setup. Thanks!
