### ISSUE TITLE
Enable edgeTPU support for use with ZMeventnotification

### ISSUE THREAD

**Issue by peetipablo** [dlandon/zoneminder#128]
Hello,

In the latest version of zmeventnotification server I see that the developer has implemented using the coral TPU as an option for hardware image processing.  It seems that a certain variable needs to be invoked for the install.sh script per the [documentation:](https://zmeventnotification.readthedocs.io/en/stable/guides/hooks.html?highlight=coral%20TPU#option-1-automatic-install)

```
Note: If you are planning on using Google EdgeTPU support, you’ll have to invoke the script using:

sudo -H INSTALL_CORAL_EDGETPU=yes ./install.sh # and follow the prompts

EdgeTPU models are not downloaded automatically as they need special hardware.
```

Is there any way to enable building this docker container with that TPU suport?

**Comment by dlandon** [comment]
I'll have the docker create the model file, but you'll probably have to run the install file manually.

**Comment by peetipablo** [comment]
That's fine with me, I'd just like some way to use the TPU since I don't have an nvidia GPU for acceleration!

I appreciate the quick response, thanks a lot.

**Comment by dlandon** [comment]
it's difficult for the docker to load the model because of the special hardware requirements.

**Comment by PrplHaz4** [comment]
Not knowing anything about the tpu installer I would have guessed the user script feature would be useful here.

Haven't gotten a coral yet but it seems it's becoming the obvious next step for efficient object detection so I'm following along....

**Comment by dlandon** [comment]
Download the install.sh and follow the instructions you mentioned above.

**Comment by peetipablo** [comment]
Thank you!!

**Comment by cliffjao** [comment]
Has anyone gotten this working? I cloned the zmeventnotification github repo and ran install.sh from within the Docker shell. However, it seems to have trouble finding the python3-edgetpu via apt-get.

```
Installing edgetpu python libs, if needed...
E: Unable to locate package python3-edgetpu
```

Manual install shows the following:
```
root@410d49132f1b:/config/github# apt install python3-edgetpu
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3-edgetpu
```

On my host Ubuntu system, it installed no problem. How do I get this working within the Docker container?

**Comment by PrplHaz4** [comment]
> 
> 
> Has anyone gotten this working? I cloned the zmeventnotification github repo and ran install.sh from within the Docker shell. However, it seems to have trouble finding the python3-edgetpu via apt-get.
> 
> ```
> Installing edgetpu python libs, if needed...
> E: Unable to locate package python3-edgetpu
> ```
> 
> Manual install shows the following:
> 
> ```
> root@410d49132f1b:/config/github# apt install python3-edgetpu
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to locate package python3-edgetpu
> ```
> 
> On my host Ubuntu system, it installed no problem. How do I get this working within the Docker container?

Did you run `apt-get update` before installing?

**Comment by cliffjao** [comment]
> > Has anyone gotten this working? I cloned the zmeventnotification github repo and ran install.sh from within the Docker shell. However, it seems to have trouble finding the python3-edgetpu via apt-get.
> > ```
> > Installing edgetpu python libs, if needed...
> > E: Unable to locate package python3-edgetpu
> > ```
> > 
> > 
> > Manual install shows the following:
> > ```
> > root@410d49132f1b:/config/github# apt install python3-edgetpu
> > Reading package lists... Done
> > Building dependency tree
> > Reading state information... Done
> > E: Unable to locate package python3-edgetpu
> > ```
> > 
> > 
> > On my host Ubuntu system, it installed no problem. How do I get this working within the Docker container?
> 
> Did you run `apt-get update` (inside the container) before installing?

Yup, I did. I'm wondering if the difference is in Ubuntu bionic vs focal. My host system is on focal. The Docker container is bionic.

**Comment by PrplHaz4** [comment]
> 
> 
> > > Has anyone gotten this working? I cloned the zmeventnotification github repo and ran install.sh from within the Docker shell. However, it seems to have trouble finding the python3-edgetpu via apt-get.
> > > ```
> > > Installing edgetpu python libs, if needed...
> > > E: Unable to locate package python3-edgetpu
> > > ```
> > > 
> > > 
> > > Manual install shows the following:
> > > ```
> > > root@410d49132f1b:/config/github# apt install python3-edgetpu
> > > Reading package lists... Done
> > > Building dependency tree
> > > Reading state information... Done
> > > E: Unable to locate package python3-edgetpu
> > > ```
> > > 
> > > 
> > > On my host Ubuntu system, it installed no problem. How do I get this working within the Docker container?
> > 
> > 
> > Did you run `apt-get update` (inside the container) before installing?
> 
> Yup, I did. I'm wondering if the difference is in Ubuntu bionic vs focal. My host system is on focal. The Docker container is bionic.

Looks like you'll need to add the package repo first: https://coral.ai/docs/accelerator/get-started/#1a-on-linux

**Comment by cliffjao** [comment]
> > > > Has anyone gotten this working? I cloned the zmeventnotification github repo and ran install.sh from within the Docker shell. However, it seems to have trouble finding the python3-edgetpu via apt-get.
> > > > ```
> > > > Installing edgetpu python libs, if needed...
> > > > E: Unable to locate package python3-edgetpu
> > > > ```
> > > > 
> > > > 
> > > > Manual install shows the following:
> > > > ```
> > > > root@410d49132f1b:/config/github# apt install python3-edgetpu
> > > > Reading package lists... Done
> > > > Building dependency tree
> > > > Reading state information... Done
> > > > E: Unable to locate package python3-edgetpu
> > > > ```
> > > > 
> > > > 
> > > > On my host Ubuntu system, it installed no problem. How do I get this working within the Docker container?
> > > 
> > > 
> > > Did you run `apt-get update` (inside the container) before installing?
> > 
> > 
> > Yup, I did. I'm wondering if the difference is in Ubuntu bionic vs focal. My host system is on focal. The Docker container is bionic.
> 
> Looks like you'll need to add the package repo first: https://coral.ai/docs/accelerator/get-started/#1a-on-linux

@PrplHaz4 Thanks for all the help here! It seems I'm able to make progress 1 step at a time. python3-edgetpu was installed successfully, I did the usermod steps, and I followed the instructions to unplug and plug in the USB Coral device. However, I'm now getting an error on opening device:

```
root@410d49132f1b:/config/github# sudo -u www-data /var/lib/zmeventnotification/bin/zm_detect.py --config /config/hook/objectconfig.ini.debug-tpu --eventid 76549 --monitorid 4 --debug
10/27/20 12:33:07 zmesdetect_m4[1830] INF zm_detect.py:205 [---------| pyzm version: 0.1.30, ES version: 6.0.6 , OpenCV version: 4.5.0|------------]

10/27/20 12:33:07 zmesdetect_m4[1830] INF zm_detect.py:231 [Importing local classes for Object/Face]

10/27/20 12:33:33 zmesdetect_m4[1830] FAT zm_detect.py:861 [Unrecoverable error:Error in device opening (/sys/bus/usb/devices/5-3)! Traceback:Traceback (most recent call last):
  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 858, in <module>
    main_handler()
  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 329, in main_handler
    m = object_detection.Object(logger=g.logger, options=g.config)
  File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/object.py", line 31, in __init__
    self.model = tpu.Tpu(options=options, logger=logger)
  File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/coral_edgetpu.py", line 40, in __init__
    self.model = DetectionEngine(self.options.get('object_weights'))
  File "/usr/lib/python3/dist-packages/edgetpu/detection/engine.py", line 80, in __init__
    super().__init__(model_path)
  File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 92, in __init__
    self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
RuntimeError: Error in device opening (/sys/bus/usb/devices/5-3)!
]
```

**Comment by PrplHaz4** [comment]
> 
> 
> 
> @PrplHaz4 Thanks for all the help here! It seems I'm able to make progress 1 step at a time. python3-edgetpu was installed successfully, I did the usermod steps, and I followed the instructions to unplug and plug in the USB Coral device. However, I'm now getting an error on opening device:
> 
> ```
> root@410d49132f1b:/config/github# sudo -u www-data /var/lib/zmeventnotification/bin/zm_detect.py --config /config/hook/objectconfig.ini.debug-tpu --eventid 76549 --monitorid 4 --debug
> 10/27/20 12:33:07 zmesdetect_m4[1830] INF zm_detect.py:205 [---------| pyzm version: 0.1.30, ES version: 6.0.6 , OpenCV version: 4.5.0|------------]
> 
> 10/27/20 12:33:07 zmesdetect_m4[1830] INF zm_detect.py:231 [Importing local classes for Object/Face]
> 
> 10/27/20 12:33:33 zmesdetect_m4[1830] FAT zm_detect.py:861 [Unrecoverable error:Error in device opening (/sys/bus/usb/devices/5-3)! Traceback:Traceback (most recent call last):
>   File "/var/lib/zmeventnotification/bin/zm_detect.py", line 858, in <module>
>     main_handler()
>   File "/var/lib/zmeventnotification/bin/zm_detect.py", line 329, in main_handler
>     m = object_detection.Object(logger=g.logger, options=g.config)
>   File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/object.py", line 31, in __init__
>     self.model = tpu.Tpu(options=options, logger=logger)
>   File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/coral_edgetpu.py", line 40, in __init__
>     self.model = DetectionEngine(self.options.get('object_weights'))
>   File "/usr/lib/python3/dist-packages/edgetpu/detection/engine.py", line 80, in __init__
>     super().__init__(model_path)
>   File "/usr/lib/python3/dist-packages/edgetpu/basic/basic_engine.py", line 92, in __init__
>     self._engine = BasicEnginePythonWrapper.CreateFromFile(model_path)
> RuntimeError: Error in device opening (/sys/bus/usb/devices/5-3)!
> ]
> ```

You will need to get the device into the container somehow (if you haven't already)...

Maybe use `--privileged` and `-v /dev/bus/usb:/dev/bus/usb`

**Comment by gfro84** [comment]
-v /dev/bus/usb:/dev/bus/usb

Seems the obvious way to do it but doesn't mean it would necessarily work. Be good to hear if and how you get it going

**Comment by gfro84** [comment]
@cliffjao great, thanks for the update. I know what my Saturday project is now.

Your results are the opposite to what I had expected, @pliablepixels zmeventserver documentation mentions the API being clunky.

**Comment by cliffjao** [comment]
> @cliffjao great, thanks for the update. I know what my Saturday project is now.
> 
> Your results are the opposite to what I had expected, @pliablepixels zmeventserver documentation mentions the API being clunky.

I think it's actually mentioned under the Performance Comparison section of https://zmeventnotification.readthedocs.io/en/latest/guides/hooks.html.

**Comment by faspina** [comment]
> 
> 
> Yup, I got it going. The following worked:
> 
> ```
> --privileged \
> -v /dev/bus/usb:/dev/bus/usb \
> ```
> 
> The fun part is that after all this work, using the TPU via the docker container is actually 1 second slower than YoloV3 CPU, probably because of the model over USB loading penalty. I switched over to MLAPI, and it's much faster. With MLAPI, zm_detect.py takes 1.4s on the TPU and 3.2s on YoloV3 CPU. My recommendation for anyone that comes across this is to just switch over to using MLAPI and don't bother trying to get the TPU working within the ZM Docker instance.

How did you get it working wiht MLAPI, do you have a specific MLAPI docker installed tied to the TPU

**Comment by cliffjao** [comment]
> > Yup, I got it going. The following worked:
> > ```
> > --privileged \
> > -v /dev/bus/usb:/dev/bus/usb \
> > ```
> > 
> > 
> > The fun part is that after all this work, using the TPU via the docker container is actually 1 second slower than YoloV3 CPU, probably because of the model over USB loading penalty. I switched over to MLAPI, and it's much faster. With MLAPI, zm_detect.py takes 1.4s on the TPU and 3.2s on YoloV3 CPU. My recommendation for anyone that comes across this is to just switch over to using MLAPI and don't bother trying to get the TPU working within the ZM Docker instance.
> 
> How did you get it working wiht MLAPI, do you have a specific MLAPI docker installed tied to the TPU

I'm just running MLAPI on the host machine, without docker. The MLAPI Docker github is pretty out of date.

**Comment by gfro84** [comment]
I too did what @cliffjao did, install MLAPI on the host and connect to it via the relevant section in objectconfig.ini on the docker. MLAPI is an easy install, good instructions from @pliablepixels. 

So far, im not impressed with the results from the Google coral usb device due to big increase in false positives. I use object detection only. 

I found accuracy running yoloV3 within the docker on the CPU to be superior. 

Fun part was getting it going I suppose...

**Comment by faspina** [comment]
I am Running zoneminder in unraid. I worked on building my own docker container for mlapi that I can use with the coral edge tpu. I don’t get the tpu until Monday from Amazon but I did manage to get mlapi running in docker with yolov3 models . It’s faster.

**Comment by paularmstrong** [comment]
Can someone write out the actual steps for getting a coral EDGETPU working in this docker container? There are a bunch of disparate instructions between the coral.ai site and the zmeventnotification docs, but I can't seem to pull them together quite right. I've installed the apt packages, cloned the zmeventnotification repo and installed it with the var on, but I still get errors:

```

  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 323, in main_handler,
Dec  4 08:14:37 03cf868f1d58 /zm_detect.py[1291]: FAT [zmesdetect_m1] [Unrecoverable error:No module named 'pycoral' Traceback:Traceback (most recent call last):,
],
  File "/var/lib/zmeventnotification/bin/zm_detect.py", line 852, in <module>,
    main_handler(),
    m = object_detection.Object(logger=g.logger, options=g.config),
  File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/object.py", line 33, in __init__,
    import pyzm.ml.coral_edgetpu as tpu,
  File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/coral_edgetpu.py", line 14, in <module>,
    from pycoral.adapters import common,
ModuleNotFoundError: No module named 'pycoral'
```

**Comment by pliablepixels** [comment]
If you are using dlandon's docker you should not have to clone zmeventnotification at all. My master version migrates to using Google's new libraries which is why you are seeing this error. 

If you do go down the route of cloning master (because you are looking for some functionality that may not be present in dlandon's image) then you should be reading https://zmeventnotification.readthedocs.io/en/latest/guides/hooks.html#installation which explains exactly what you need to do.

**Comment by paularmstrong** [comment]
> If you are using dlandon's docker you should not have to clone zmeventnotification at all. My master version migrated to using Google's new libraries which is why you are seeing this error.

Okay, so I was seeing many other errors before cloning. Do you or anyone else have step by step instructions for getting EdgeTPU to work?
