### ISSUE TITLE
update to 1.32.0

### ISSUE THREAD

**Issue by zhuykovkb** [dlandon/zoneminder#13]
Hello.

Current version of your zoneminder is 1.30.4, but in upstream (https://github.com/ZoneMinder/zoneminder) - 1.32.0. There are many fixes and a lot of new functions (such as mp4 video recording). Could you upgrade 1.30.4 -> 1.32.0 or latest?

**Comment by dlandon** [comment]
Not right now.  I need an official package to be built and available in a repository and then I will have to build a test Docker and work through the issues.  Zoneminder has always been very difficult to upgrade in place in a Docker and I will have to work all that out.  I want to wait for the release to be out for a while so the bugs/problems can be worked out.

If this doesn't work for you, feel free to build your own Docker.
