### ISSUE TITLE
Access Zoneminder from Chrome?

### ISSUE THREAD

**Issue by danieldbird** [dlandon/zoneminder#130]
I get the following error. Any help would be appreciated.

Your connection is not private
Attackers might be trying to steal your information from 192.168.1.2 (for example, passwords, messages or credit cards). Learn more
NET::ERR_CERT_INVALID

![image](https://user-images.githubusercontent.com/2720368/97132391-ac26c300-17ab-11eb-9579-dd6f9a8dcf3c.png)

**Comment by dlandon** [comment]
Google is warning you about a self signed certificate.  Click 'Advanced' and you can get past it.

**Comment by danieldbird** [comment]
Thanks, however clicking advanced in Chrome specifically no longer gives the option to "I know the risks, continue anyway" anymore. Safari can, Firefox I have not tested. Cheers.

**Comment by danieldbird** [comment]
To anyone else facing the same issue in newer versions of Chrome where there is no "I understand the risks and proceed" option. Simply type with your keyboard anywhere on the page the following and the page will load:
"thisisunsafe" (without quotes)
The does effectively the same thing as the knowing the risks and proceeding button, but is now hidden behind this transparent command.
Also shows no matter where you are, Google is keylogging you.
