### ISSUE TITLE
Missing libraries for pushover (Event Notification Server )

### ISSUE THREAD

**Issue by wayofka** [dlandon/zoneminder#132]
Using pushover in Event Notification Server not working out of box. Script /var/lib/zmeventnotification/bin/pushapi_pushover.py  need some extra libraries (pyzm).
Just add to Dockerfile
```
apt install python3-pip python3-dev gcc
pip3 install pyzm
```
gcc is need it, because psutil, and can be remove from image after pyzm installation

and 
Or you can mount libraries to container and set PYTHONPATH to script
run container with mount
`-v "/srv/zoneminder/zoneminder_pylibs:/var/lib/zmeventnotification/bin/libs:ro,Z" \`
in zmeventnotification.ini
change 
`api_push_script=PYTHONPATH=/var/lib/zmeventnotification/bin/libs /var/lib/zmeventnotification/bin/pushapi_pushover.py`

SFTP upload seem similar problem, in image missing some perl libraries. A don't use it now, can't confirm now. 
You should add to install perl modules: Archive::Tar, Archive::Zip, Net::FTP, Net::SFTP  to Dockerfile
```
perl -MCPAN -e "force install Archive::Tar" && \
perl -MCPAN -e "force install Archive::Zip" && \
perl -MCPAN -e "force install Net::FTP" && \
perl -MCPAN -e "force install Net::SFTP" && \
```

**Comment by dlandon** [comment]
Will be added to next release of the docker.

**Comment by dlandon** [comment]
Don't know that much about perl modules, but I get this error:

Can't locate object method "install" via package "Archive::Tar" at -e line 1.

**Comment by dlandon** [comment]
pyzm is already installed by setup.py.
