### ISSUE TITLE
After upgrading to new docker image

### ISSUE THREAD

**Issue by Ranger21** [dlandon/zoneminder#135]
After upgrading to new docker image with new zmeventnotification server i  took new objectconfig.ini and put all my old configs to there, but i still get these errors, what they can mean?

I have 15 monitors all configured to zmeventnotification server

Unrecoverable error:Already locked Traceback:Traceback (most recent call last): File "/var/lib/zmeventnotification/bin/zm_detect.py", line 852, in <module> main_handler() File "/var/lib/zmeventnotification/bin/zm_detect.py", line 424, in main_handler b, l, c = m.detect(original_image) File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/object.py", line 54, in detect b,l,c = self.model.detect(image) File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/yolo.py", line 111, in detect self.acquire_lock() File "/usr/local/lib/python3.6/dist-packages/pyzm/ml/yolo.py", line 41, in acquire_lock self.lock.acquire() File "/usr/local/lib/python3.6/dist-packages/portalocker/utils.py", line 318, in acquire assert not self.lock, 'Already locked'AssertionError: Already locked

**Comment by dlandon** [comment]
Ask for support on the Zoneminder forum.
