### ISSUE TITLE
Deleting/overwriting custom config files in /etc

### ISSUE THREAD

**Issue by TheOneOgre** [dlandon/zoneminder#136]
Whenever the image is updated or has any changes made that require a new compose, any configuration inside /etc/zm/conf.d gets erased or overwritten. The same goes for /etc/mysql/my.cnf

These files are necessary for setting Zoneminder up in a multi-server configuration. While I am working on a workaround using custom scripts, especially for my.cnf, it would be really nice to be able to have at least the customer files in /zm/conf.d to not be deleted with small changes to the docker container.

Maybe I'm missing something but it seems to just be a kind of bug. Maybe write in an environment variable to set options in conf.d and my.cnf specifically to enable multi-server configuration?

**Comment by dlandon** [comment]
That's the nature of a docker.  When it is updated, any changes inside the docker are lost.  That's why the config/ folder holds all that can change so it is persistent on an update or removal/re-install of the docker.  My suggestion is to create a script using the user script feature that will make the changes you need inside the docker whenever the docker is started.  I'm not inclined to add yet another environment variable.  There are too many as it is.

**Comment by PrplHaz4** [comment]
You should be able to mount both of those files as individual persistent volumes to have the changes persist....
```
-v ./zmconf.d:/etc/zm/conf.d
-v ./mysqlmy.cnf:/etc/mysql/my.cnf
```

**Comment by TheOneOgre** [comment]
> You should be able to mount both of those files as individual persistent volumes to have the changes persist....
> 
> ```
> -v ./zmconf.d:/etc/zm/conf.d
> -v ./mysqlmy.cnf:/etc/mysql/my.cnf
> ```

Interesting. I'm still learning docker and that seems like it could for sure work.

Does it matter that conf.d is a directory and my.cnf is a file? Would the commands be different?

I tried reading the docker documentation about mounts and couldn't really find much helpful information about this specifically or how to apply this to my unraid config.

Great suggestion though.

**Comment by PrplHaz4** [comment]
> 
> Does it matter that conf.d is a directory and my.cnf is a file? Would the commands be different?

Sorry that’s An error on my part. Yes it does matter. You can map the whole directory but it’s probably safer to start with just the file you want to override.

**Comment by TheOneOgre** [comment]
> > Does it matter that conf.d is a directory and my.cnf is a file? Would the commands be different?
> 
> Sorry that’s An error on my part. Yes it does matter. You can map the whole directory but it’s probably safer to start with just the file you want to override.

Understandable. Well great news! I added the appropriate -v command to both of my dockers (running a multi-server install) and now when updating the config for the docker, all changes stay present! The only thing I'm unsure about is, if zoneminder gets and update and needs to add lines to my.cnf for the mysql server, how is it going to react to this? And can the mysql/conf.d/ directory be used like the /zm/conf.d/ directory? 

Those questions are more for the creator of zoneminder than dlandon or yourself, but just something to think about. Thank you very much @PrplHaz4 !!
