### ISSUE TITLE
Redirect default apache

### ISSUE THREAD

**Issue by nthny** [dlandon/zoneminder#137]
My old setup of zm died so I used this container to do my fresh install. Everything is working ok but I have a question, how to disabled o redirect the default apache web to domain.com:8443/zm?.

**Comment by Tony763** [comment]
Hi, the same go for me: I used: `-p 8080:80/tcp` as specified in README.md and only default apache page is shown.

**Comment by dlandon** [comment]
Readme is wrong.  It is /zm not /tcp.
