### ISSUE TITLE
Cuda and missing *.pl in /usr/bin 

### ISSUE THREAD

**Issue by Tony763** [dlandon/zoneminder#139]
Hi, I have a little problem with docker image.
When I want to add CUDA suport, I lost installation files of ZM.

My steps:
```
docker pull dlandon/zoneminder

docker run -d --name="Zoneminder2" \
--net="bridge" \
--privileged="true" \
-p 8070:80/tcp \
-p 8443:443/tcp \
-p 9000:9000/tcp \
-e TZ="Europe/Prague" \
-e SHMEM="50%" \
-e PUID="99" \
-e PGID="100" \
-e INSTALL_HOOK="0" \
-e INSTALL_FACE="0" \
-e INSTALL_TINY_YOLOV3="0" \
-e INSTALL_YOLOV3="0" \
-e INSTALL_TINY_YOLOV4="0" \
-e INSTALL_YOLOV4="0" \
-e MULTI_PORT_START="0" \
-e MULTI_PORT_END="0" \
-v "/home/tony/Zoneminder":"/config":rw \
-v "/home/tony/Zoneminder/data":"/var/cache/zoneminder":rw \
dlandon/zoneminder
```
Zm up and running.
```
docker exec -it Zoneminder sh
cd /home
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
sudo echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /" | sudo tee -a /etc/apt/sources.list
sudo echo "deb http://cz.archive.ubuntu.com/ubuntu/ groovy main restricted" | sudo tee -a /etc/apt/sources.list
sudo echo "deb-src http://cz.archive.ubuntu.com/ubuntu/ groovy main restricted" | sudo tee -a /etc/apt/sources.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3B4FE6ACC0B21F32
sudo apt update
sudo apt -y install nano dialog
#sudo apt upgrade -y # Do not do
sudo apt -y install cuda cuda-drivers cuda-drivers-455
```
At this point all *.pl files except ` zmeventnotification.pl` and container refuse to start.

**Comment by dlandon** [comment]
That is not the way to do it.  Look at the config/opencv/opencv.sh on how to compile opencv with cuda support.

**Comment by Tony763** [comment]
Okay , I am blind or I miss some step. I removed container and started from scratch. I used a docker run ...from above but I cannot find a option to turn on hooks in config.

**Comment by dlandon** [comment]
-e INSTALL_HOOK="1" \

**Comment by Tony763** [comment]
Back and sound. Steps:
```
docker exec -it Zoneminder2 sh
apt install nano
cd config/opencv/
nano opencv.sh   #Download appreciate files and edit fields
./opencv.sh
python3
import cv2
Ctrl+D
nvidia-smi    # Not found
sudo apt -y install cuda cuda-drivers cuda-drivers-455
sudo echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /" | sudo tee -a /etc/apt/sources.list
sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
sudo apt update
sudo apt upgrade

nvidia-smi   # Produce cuda/drivers mismatch 

sudo echo "deb-src http://cz.archive.ubuntu.com/ubuntu/ groovy main restricted" | sudo tee -a /etc/apt/sources.list
sudo echo "deb http://cz.archive.ubuntu.com/ubuntu/ groovy main restricted" | sudo tee -a /etc/apt/sources.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3B4FE6ACC0B21F32
sudo apt update

sudo apt --only-upgrade install cuda cuda-drivers cuda-drivers-455

nvidia-smi  # OK
exit
docker commit Zoneminder2 zon_v3             # Safe
```
Next step to do
`ffmpeg -hwaccels` # Add cuda

**Comment by mihaiblaga89** [comment]
working on the same thing at the moment. As soon as I have ffmpeg + cuda I'll report back

**Comment by Tony763** [comment]
FFmpeg and opencv compiled with cuda, now I struct with face detection:
`Unrecoverable error:libopenblas.so.0: cannot open shared object file: No such file or directory Traceback:Traceback (most recent call last): File "/var/lib/zmeventnotification/bin/zm_detect.py", line 852, in <module> main_handler() File "/var/lib/zmeventnotification/bin/zm_detect.py", line 331, in main_handler import pyzm.ml.face as face File "/usr/local/lib/python3.8/dist-packages/pyzm/ml/face.py", line 3, in <module> import pyzm.ml.face_train as train File "/usr/local/lib/python3.8/dist-packages/pyzm/ml/face_train.py", line 11, in <module> import face_recognition File "/usr/local/lib/python3.8/dist-packages/face_recognition/__init__.py", line 7, in <module> from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance File "/usr/local/lib/python3.8/dist-packages/face_recognition/api.py", line 4, in <module> import dlib File "/usr/local/lib/python3.8/dist-packages/dlib/__init__.py", line 19, in <module> from _dlib_pybind11 import *ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory`

**Comment by dlandon** [comment]
Turn on the environment variable to load face recognition:
-e INSTALL_FACE="1" \

**Comment by Tony763** [comment]
Even if I added it manually by:
```
sudo apt-get install libopenblas-dev liblapack-dev libblas-dev
sudo -H pip3 install face_recognition
```

**Comment by dlandon** [comment]
Don't do it manually.  Let the docker do the installation.

**Comment by Tony763** [comment]
An will it install it with libopenblas-dev ? As described here [zmeventnotification.readthedocs.io/](https://zmeventnotification.readthedocs.io/en/latest/guides/hooks.html?highlight=face_recognition#make-sure-opencv-works)

**Comment by Tony763** [comment]
Finnaly works, path to libopenblas.so.0 was missing in PYTHONPATH.  @dlandon Thanks for this awesome docker image

**Comment by mihaiblaga89** [comment]
@dlandon @Tony763 managed to find a solution to have Nvidia drivers and ffmpeg with nvenc enabled, if you're interested. I added this in my userscript

```
# add ffmpeg-nvenc ppa
add-apt-repository ppa:cybermax-dexter/ffmpeg-nvenc -y
add-apt-repository ppa:cybermax-dexter/sdl2-backport -y
apt-get update

# install ffmpeg + deps and ubuntu-drivers
apt-get install -y --allow-downgrades ubuntu-drivers-common ffmpeg=7:4.3-2nvenc1~18.04 libavdevice58=7:4.3-2nvenc1~18.04 libavcodec58=7:4.3-2nvenc1~18.04 libavfilter7=7:4.3-2nvenc1~18.04 libavformat58=7:4.3-2nvenc1~18.04 libavresample4=7:4.3-2nvenc1~18.04 libavutil56=7:4.3-2nvenc1~18.04 libpostproc55=7:4.3-2nvenc1~18.04 libswresample3=7:4.3-2nvenc1~18.04 libswscale5=7:4.3-2nvenc1~18.04
# autoinstall nvidia drivers
ubuntu-drivers autoinstall
```

**Comment by Tony763** [comment]
@mihaiblaga89 How did you set DecoderHWAccelName (?) and DecoderHWAccelDevice (?) in monitor and  FFMPEG_OUTPUT_OPTIONS and FFMPEG_INPUT_OPTIONS in Options > Images?

**Comment by mihaiblaga89** [comment]
I have AccelName set as cuda but I'm getting "Failed to get HW surface format for cuda" in the logs. This most likely is because ZM still looks for the old `libav*` libraries which do not have cuda support. https://github.com/ZoneMinder/zoneminder/issues/2847 https://forums.zoneminder.com/viewtopic.php?t=29105

**Comment by dlandon** [comment]
Post your issues on the Zoneminder forum for better support.
