### ISSUE TITLE
ssmtp not working :( 

### ISSUE THREAD

**Issue by Gudzikgit** [dlandon/zoneminder#14]
Hi, sending notifications via ssmtp is not working.
I set up this guide: https://wiki.zoneminder.com/How_to_get_ssmtp_working_with_Zoneminder

Oct 18 15:40:11 zoneminder zmfilter_3 [1012]: INF [Sending notification email 'ZoneMinder: Alarm - AxisIn4-456 (62 - 28 15)']
Oct 18 15:40:11 zoneminder zmfilter_3 [1012]: ERR [Unable to send email: error closing / usr / lib / sendmail: (exit 256)]

Earned after adding the user www-data to the mail group and chmod -R 777 / config / ssmtp and restart apache and zoneminder from docker console

After new install:
root@zoneminder:/# tail -f /var/log/mail.log

> Oct 18 17:00:25 zoneminder sSMTP[886]: /etc/ssmtp/ssmtp.conf not found
> Oct 18 17:00:26 zoneminder sSMTP[886]: Unable to locate mailhub
> Oct 18 17:00:26 zoneminder sSMTP[886]: Cannot open mailhub:25
> Oct 18 17:01:26 zoneminder sSMTP[896]: /etc/ssmtp/ssmtp.conf not found
> Oct 18 17:01:26 zoneminder sSMTP[896]: Unable to locate mailhub
> Oct 18 17:01:26 zoneminder sSMTP[896]: Cannot open mailhub:25

Making changes: 

> root@zoneminder:/# usermod -a -G mail www-data
> root@zoneminder:/# chmod -R 777 /config/ssmtp
> root@zoneminder:/# service zoneminder stop
> Stopping ZoneMinder:
> 10/18/18 17:06:58.942959 zmpkg[925].INF [main:57] [Command: status]
> 10/18/18 17:06:58.949272 zmpkg[925].INF [main:305] [Sanity checking States table...]
> 10/18/18 17:06:58.956833 zmpkg[925].INF [main:97] [Command: status]
> 10/18/18 17:06:59.242767 zmpkg[932].INF [main:57] [Command: stop]
> 10/18/18 17:06:59.247079 zmpkg[932].INF [main:305] [Sanity checking States table...]
> 10/18/18 17:06:59.250929 zmpkg[932].INF [main:97] [Command: stop]
> ZoneMinder stopped successfully
> 
> root@zoneminder:/# service apache2 stop
>  * Stopping Apache httpd web server apache2  *
> root@zoneminder:/# service apache2 start
>  * Starting Apache httpd web server apache2  *
> root@zoneminder:/# service zoneminder start
> Starting ZoneMinder:
> 10/18/18 17:07:39.138213 zmpkg[1019].INF [main:57] [Command: start]
> 10/18/18 17:07:39.144336 zmpkg[1019].INF [main:305] [Sanity checking States table...]
> 10/18/18 17:07:39.147962 zmpkg[1019].INF [main:97] [Command: start]
> 10/18/18 17:07:43.425503 zmpkg[1019].INF [main:205] [Single server configuration detected. Starting up services.]
> ZoneMinder started successfully
> 
> root@zoneminder:/# tail -f /var/log/mail.log
> Oct 18 17:03:26 zoneminder sSMTP[905]: Cannot open mailhub:25
> Oct 18 17:04:26 zoneminder sSMTP[908]: /etc/ssmtp/ssmtp.conf not found
> Oct 18 17:04:26 zoneminder sSMTP[908]: Unable to locate mailhub
> Oct 18 17:04:26 zoneminder sSMTP[908]: Cannot open mailhub:25
> Oct 18 17:05:26 zoneminder sSMTP[911]: /etc/ssmtp/ssmtp.conf not found
> Oct 18 17:05:26 zoneminder sSMTP[911]: Unable to locate mailhub
> Oct 18 17:05:26 zoneminder sSMTP[911]: Cannot open mailhub:25
> Oct 18 17:06:26 zoneminder sSMTP[919]: /etc/ssmtp/ssmtp.conf not found
> Oct 18 17:06:26 zoneminder sSMTP[919]: Unable to locate mailhub
> Oct 18 17:06:26 zoneminder sSMTP[919]: Cannot open mailhub:25
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set Root="Gmaillogin@gmail.com"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set MailHub="smtp.gmail.com"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set RemotePort="587"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set HostName="localhost"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set RewriteDomain="gmail.com"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set FromLineOverride="True"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set UseSTARTTLS="True"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set UseTLS="True"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set AuthUser="Gmaillogin@gmail.com"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set AuthPass="GmailPassword"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: Set MailHub="smtp.gmail.com"
> Oct 18 17:08:05 zoneminder sSMTP[1121]: via SMTP Port Number="587"
> Oct 18 17:08:06 zoneminder sSMTP[1121]: Creating SSL connection to host
> Oct 18 17:08:06 zoneminder sSMTP[1121]: 220 smtp.gmail.com ESMTP r13-v6sm4564862ljc.64 - gsmtp
> Oct 18 17:08:06 zoneminder sSMTP[1121]: EHLO localhost
> Oct 18 17:08:06 zoneminder sSMTP[1121]: 250 SMTPUTF8
> Oct 18 17:08:06 zoneminder sSMTP[1121]: STARTTLS
> Oct 18 17:08:06 zoneminder sSMTP[1121]: 220 2.0.0 Ready to start TLS
> Oct 18 17:08:06 zoneminder sSMTP[1121]: SSL connection using ECDHE_RSA_AES_128_GCM_SHA256
> Oct 18 17:08:06 zoneminder sSMTP[1121]: EHLO localhost
> Oct 18 17:08:06 zoneminder sSMTP[1121]: 250 SMTPUTF8
> Oct 18 17:08:06 zoneminder sSMTP[1121]: AUTH LOGIN
> Oct 18 17:08:06 zoneminder sSMTP[1121]: 334 123123
> Oct 18 17:08:06 zoneminder sSMTP[1121]: 123123
> Oct 18 17:08:06 zoneminder sSMTP[1121]: 334 123123
> Oct 18 17:08:06 zoneminder sSMTP[1121]: UUFGQ0hjellEVA==
> Oct 18 17:08:06 zoneminder sSMTP[1121]: 235 2.7.0 Accepted
> Oct 18 17:08:06 zoneminder sSMTP[1121]: MAIL FROM:<root@localhost>
> Oct 18 17:08:06 zoneminder sSMTP[1121]: 250 2.1.0 OK r13-v6sm4564862ljc.64 - gsmtp
> Oct 18 17:08:06 zoneminder sSMTP[1121]: RCPT TO:<UserLogi@gmail.com>
> Oct 18 17:08:06 zoneminder sSMTP[1121]: 250 2.1.5 OK r13-v6sm4564862ljc.64 - gsmtp
> Oct 18 17:08:06 zoneminder sSMTP[1121]: DATA
> Oct 18 17:08:07 zoneminder sSMTP[1121]: 354  Go ahead r13-v6sm4564862ljc.64 - gsmtp
> Oct 18 17:08:07 zoneminder sSMTP[1121]: Received: by localhost (sSMTP sendmail emulation); Thu, 18 Oct 2018 17:08:05 +0300
> Oct 18 17:08:07 zoneminder sSMTP[1121]: Content-Transfer-Encoding: binary
> Oct 18 17:08:07 zoneminder sSMTP[1121]: Content-Type: multipart/mixed; boundary="_----------=_153987168510850"
> Oct 18 17:08:07 zoneminder sSMTP[1121]: MIME-Version: 1.0
> Oct 18 17:08:07 zoneminder sSMTP[1121]: X-Mailer: MIME::Lite 3.030 (F2.85; T2.12; A2.13; B3.15; Q3.13)
> Oct 18 17:08:07 zoneminder sSMTP[1121]: Date: Thu, 18 Oct 2018 17:08:05 +0300
> Oct 18 17:08:07 zoneminder sSMTP[1121]: From: root@localhost
> Oct 18 17:08:07 zoneminder sSMTP[1121]: To: UserLogi@gmail.com
> Oct 18 17:08:07 zoneminder sSMTP[1121]: Subject: ZoneMinder: Alarm - AxisIn4-458 (50 - 40 5)
> Oct 18 17:08:07 zoneminder sSMTP[1121]:
> Oct 18 17:08:07 zoneminder sSMTP[1121]: This is a multi-part message in MIME format.
> Oct 18 17:08:07 zoneminder sSMTP[1121]:
> Oct 18 17:08:07 zoneminder sSMTP[1121]: --_----------=_153987168510850
> Oct 18 17:08:07 zoneminder sSMTP[1121]: Content-Disposition: inline
> Oct 18 17:08:07 zoneminder sSMTP[1121]: Content-Transfer-Encoding: 8bit
> Oct 18 17:08:07 zoneminder sSMTP[1121]: Content-Type: text/plain
> Oct 18 17:08:07 zoneminder sSMTP[1121]:
> Oct 18 17:08:07 zoneminder sSMTP[1121]:       Hello,
> Oct 18 17:08:07 zoneminder sSMTP[1121]:
> Oct 18 17:08:07 zoneminder sSMTP[1121]:     An alarm has been detected on your installation of the ZoneMinder.
> Oct 18 17:08:07 zoneminder sSMTP[1121]:
> Oct 18 17:08:07 zoneminder sSMTP[1121]:       The details are as follows :-
> Oct 18 17:08:07 zoneminder sSMTP[1121]:
> Oct 18 17:08:07 zoneminder sSMTP[1121]:       Monitor  : AxisIn4
> Oct 18 17:08:07 zoneminder sSMTP[1121]:       Event Id : 458
> Oct 18 17:08:07 zoneminder sSMTP[1121]:       Length   : 1.75
> Oct 18 17:08:07 zoneminder sSMTP[1121]:       Frames   : 13 (5)
> Oct 18 17:08:07 zoneminder sSMTP[1121]:       Scores   : t201 m50 a40
> Oct 18 17:08:07 zoneminder sSMTP[1121]:
> Oct 18 17:08:07 zoneminder sSMTP[1121]:       This alarm was matched by the AlarmSend filter and can be viewed at https://192.168.10.237:8443/zm?view=event&mode=stream&mid=3&eid=458
> Oct 18 17:08:07 zoneminder sSMTP[1121]:
> Oct 18 17:08:07 zoneminder sSMTP[1121]:       ZoneMinder
> Oct 18 17:08:07 zoneminder sSMTP[1121]: --_----------=_153987168510850--
> Oct 18 17:08:08 zoneminder sSMTP[1121]: .
> Oct 18 17:08:10 zoneminder sSMTP[1121]: 250 2.0.0 OK 1539871690 r13-v6sm4564862ljc.64 - gsmtp
> Oct 18 17:08:10 zoneminder sSMTP[1121]: QUIT
> Oct 18 17:08:10 zoneminder sSMTP[1121]: 221 2.0.0 closing connection r13-v6sm4564862ljc.64 - gsmtp
> Oct 18 17:08:10 zoneminder sSMTP[1121]: Sent mail for root@localhost (221 2.0.0 closing connection r13-v6sm4564862ljc.64 - gsmtp) uid=33 username=www-data outbytes=1191
> ^C
> root@zoneminder:/#

**Comment by dlandon** [comment]
Fixed in the next release.
