### ISSUE TITLE
Multistage Docker Image Unnecessary

### ISSUE THREAD

**Issue by alexyao2015** [dlandon/zoneminder#142]
6c6e4d4deb0596786df49b0f22d57194d5792002
This commit isn't necessary and has made the build inefficient. The original Dockerfile before this commit was best practice. Typically, multistage builds are used for compiling a program and leaving out the extra things that had to be downloaded in the process.

I would suggest undoing this commit.

**Comment by dlandon** [comment]
From what I have read, the multistage is more efficient.

**Comment by alexyao2015** [comment]
Under very specific circumstances, it is. Check out this [here](https://www.docker.com/blog/advanced-dockerfiles-faster-builds-and-smaller-images-using-buildkit-and-multistage-builds/) for details.
