### ISSUE TITLE
Feature request: copy/link /etc/zm/es_rules.json

### ISSUE THREAD

**Issue by currand** [dlandon/zoneminder#143]
Zoneminder supports additional event rules via a JSON file in /etc/zm. This should be located in the persistent /mnt/Zoneminder/es_rules.conf and linked on startup. On my own system, I've added the following to `/etc/my_init.d/40_firstrun.sh`:

```
# Handle the es_rules.json
if [ -f /config/es_rules.json ]; then
        echo "Linking es_rules.json"
        rm -rf /etc/zm/es_rules.json
        ln -sf /config/es_rules.json /etc/zm/es_rules.json
fi
```

**Comment by dlandon** [comment]
Included in the next release.
