### ISSUE TITLE
OpenCV recompiles each time I modify a environment variable / container parameter.

### ISSUE THREAD

**Issue by Erozionn** [dlandon/zoneminder#144]
As the title says, each time I modify or add a environment variable to the container in docker-compose OpenCV redownloads/recompiles even though it is unrelated to OpenCV (eg. I changed MULTI_PORT_START, MULTI_PORT_END environment variables).

Is there anyway to prevent this behaviour? OpenCV compiling takes a very long time and sometimes makes my server lock up entirely.

**Comment by dlandon** [comment]
Set INSTALL_HOOK="0".

**Comment by Erozionn** [comment]
Wow. Amazing. Thank you so much!
