### ISSUE TITLE
Also issue with the latest image

### ISSUE THREAD

**Issue by cm86** [dlandon/zoneminder#148]
Hello,
after pulling the latest image from  docker i have the following messages in my container log.

`
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...

*** Running /etc/my_init.d/05_set_the_time.sh...
Setting the timezone to : Europe/Berlin

Current default time zone: 'Europe/Berlin'
Local time is now: Sat Jan 2 20:19:15 CET 2021.
Universal Time is now: Sat Jan 2 19:19:15 UTC 2021.

Date: Sat Jan 2 20:19:15 CET 2021
*** Running /etc/my_init.d/06_set_php_time.sh...
*** Running /etc/my_init.d/07_set_dri_permissions.sh...
Granting permissions on /dev/dri/* devices...
Generated a new group called: videobKITQ4aw with id: 18 to match existing group on: /dev/dri/renderD128
Added user www-data to group videobKITQ4aw so that it has permission to use: /dev/dri/renderD128
The www-data user already has appropriate permissions on /dev/dri/card0
*** Running /etc/my_init.d/10_syslog-ng.init...
[2021-01-02T20:19:15.940022] WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng 3.25 format at your time of convenience. To upgrade the configuration, please review the warnings about incompatible changes printed by syslog-ng, and once completed change the @version header at the top of the configuration file; config-version='3.13'
[2021-01-02T20:19:16.069117] WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;
Jan 2 20:19:16 c977f0de0aed syslog-ng[72]: syslog-ng starting up; version='3.25.1'
Jan 2 20:19:16 c977f0de0aed syslog-ng[72]: WARNING: log-fifo-size() works differently starting with syslog-ng 3.22 to avoid dropping flow-controlled messages when log-fifo-size() is misconfigured. From now on, log-fifo-size() only affects messages that are not flow-controlled. (Flow-controlled log paths have the flags(flow-control) option set.) To enable the new behaviour, update the @version string in your configuration and consider lowering the value of log-fifo-size().;
*** Running /etc/my_init.d/20_apt_update.sh...
Performing updates...
Hit:1 http://ppa.launchpad.net/iconnor/zoneminder-1.34/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [109 kB]
Hit:5 http://ppa.launchpad.net/ondrej/php/ubuntu focal InRelease
Get:6 http://archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Fetched 324 kB in 1s (258 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
*** Running /etc/my_init.d/30_gen_ssl_keys.sh...
using existing keys in "/config/keys"
*** Running /etc/my_init.d/40_firstrun.sh...
Using existing conf folder
Moving zm.conf to config folder
Moving zmeventnotification.ini
Moving secrets.ini
Moving opencv.sh
Moving debug_opencv.sh
Moving the event notification server
Moving the pushover api
Moving es_rules.json
Using existing ssmtp folder
Using existing mysql database folder
Copy /config/control/ scripts to /usr/share/perl5/ZoneMinder/Control/
Copy /config/conf/ scripts to /etc/zm/conf.d/
Creating symbolink links
Moving zmeventnotification.ini
Moving secrets.ini
Moving opencv.sh
Moving debug_opencv.sh
Moving the event notification server
Moving the pushover api
Moving es_rules.json
Using existing ssmtp folder
Using existing mysql database folder
Copy /config/control/ scripts to /usr/share/perl5/ZoneMinder/Control/
Copy /config/conf/ scripts to /etc/zm/conf.d/
Creating symbolink links
Using existing data directory for events
Using existing data directory for images
Using existing data directory for temp
Using existing data directory for cache
no crontab for root
Starting services...
* Starting Apache httpd web server apache2
*
* Starting MariaDB database server mysqld
Jan 2 20:19:36 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:36 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:36 c977f0de0aed web_php[656]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:36 c977f0de0aed web_php[655]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:36 c977f0de0aed web_php[656]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:36 c977f0de0aed web_php[655]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:36 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:36 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:36 c977f0de0aed web_php[656]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:36 c977f0de0aed web_php[655]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:36 c977f0de0aed web_php[656]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:36 c977f0de0aed web_php[655]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:36 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:36 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:36 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:36 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:36 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:36 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[656]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[656]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[659]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[659]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[656]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[656]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:37 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:37 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:38 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:38 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[658]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:39 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:39 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:40 c977f0de0aed web_php[659]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:40 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:40 c977f0de0aed web_php[659]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:40 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[655]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:40 c977f0de0aed web_php[655]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:40 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:40 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:40 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:40 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:40 c977f0de0aed web_php[657]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:41 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[655]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:41 c977f0de0aed web_php[655]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:41 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[657]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[658]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[922]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:41 c977f0de0aed web_php[922]: ERR [Unable to authenticate user. error decoding JWT token:Signature verification failed]
Jan 2 20:19:41 c977f0de0aed web_php[659]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[655]: FAT [Failed db connection to ]
Jan 2 20:19:41 c977f0de0aed web_php[656]: FAT [Failed db connection to ]
...fail!
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
Jan 2 20:19:54 c977f0de0aed zmupdate[1097]: ERR [Error reconnecting to db: errstr:Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) error val:]
Can't call method "prepare_cached" on an undefined value at /usr/share/perl5/ZoneMinder/Config.pm line 96.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 147.
Compilation failed in require at /usr/bin/zmupdate.pl line 73.
BEGIN failed--compilation aborted at /usr/bin/zmupdate.pl line 73.
Jan 2 20:19:54 c977f0de0aed zmupdate[1097]: ERR [Error reconnecting to db: errstr:Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) error val:]
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
Jan 2 20:19:54 c977f0de0aed zmupdate[1099]: ERR [Error reconnecting to db: errstr:Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) error val:]
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
Can't call method "prepare_cached" on an undefined value at /usr/share/perl5/ZoneMinder/Config.pm line 96.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 147.
Compilation failed in require at /usr/bin/zmupdate.pl line 73.
BEGIN failed--compilation aborted at /usr/bin/zmupdate.pl line 73.
Jan 2 20:19:54 c977f0de0aed zmupdate[1099]: ERR [Error reconnecting to db: errstr:Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) error val:]
Starting ZoneMinder:
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Database.pm line 110.
Jan 2 20:19:54 c977f0de0aed zmpkg[1109]: ERR [Error reconnecting to db: errstr:Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) error val:]
Can't call method "prepare_cached" on an undefined value at /usr/share/perl5/ZoneMinder/Config.pm line 96.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 147.
Compilation failed in require at /usr/share/perl5/ZoneMinder.pm line 33.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder.pm line 33.
Compilation failed in require at /usr/bin/zmpkg.pl line 34.
BEGIN failed--compilation aborted at /usr/bin/zmpkg.pl line 34.
Jan 2 20:19:54 c977f0de0aed zmpkg[1109]: ERR [Error reconnecting to db: errstr:Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) error val:]
ZoneMinder failed to start

*** /etc/my_init.d/40_firstrun.sh failed with status 255

*** Killing all processes...
Jan 2 20:19:54 c977f0de0aed syslog-ng[72]: syslog-ng shutting down; version='3.25.1' 
`
---------------------------------------------------------------------------------------------------------------------------------

So Zoneminder doesn't start up...

is there a way i can fix this?

mfg
Chris
(sorry for posting the whole log file, but I don't want anything missing ...)

**Comment by kabadisha** [comment]
How are you running the container?
What is your host machine?
Can you share the run command you used?

**Comment by cm86** [comment]
excuse me ...
I'm running on Unraid  6.9.0-rc2
Host Machine is a Dell T7600
The Command after looking at the privious error is...
--> [Issues with latest image](https://github.com/dlandon/zoneminder/issues/147#issuecomment-753518642)
`docker run -d --name='Zoneminder' --net='bridge' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -e 'INSTALL_HOOK'='0' -e 'INSTALL_TINY_YOLOV3'='0' -e 'INSTALL_YOLOV3'='0' -e 'INSTALL_TINY_YOLOV4'='0' -e 'INSTALL_YOLOV4'='0' -e 'INSTALL_FACE'='0' -e 'SHMEM'='25%' -p '8443:443/tcp' -p '9000:9000/tcp' -v '/mnt/user/appdata/Zoneminder':'/config':'rw' -v '/mnt/user/UnraidServer/4TB01/zoneminder/':'/var/cache/zoneminder':'rw,slave' --log-opt max-size=50m --log-opt max-file=1 'dlandon/zoneminder@sha256:25213e4ac671cba5fc92388bbb3b35db091b455cc6add0590c56f36574a82b3b'`

**Comment by cm86** [comment]
So after setting the image tag to what you have mentioned for the privious version it working again...
`dlandon/zoneminder@sha256:25213e4ac671cba5fc92388bbb3b35db091b455cc6add0590c56f36574a82b3b`

**Comment by kabadisha** [comment]
Ok, not sure if this is causing the issue but you want to replace `-e 'SHMEM'='25%'` with `--shm-size="5G"` (adjusted for how ever much ram you want to give to ZM).

This change also will work fine with the previous build.

With the latest build, the previous mechanism for allocating memory was removed, so when you updated only the default amount would have been assigned (I think Docker defaults to 64m or something).

**Comment by kabadisha** [comment]
Bear in mind, that you should probably make a backup of your config directory before you attempt the upgrade. Once the DB scripts run, there is no going back without a backup.

**Comment by kabadisha** [comment]
Theoretically, with the new build you can also remove `--privileged=true` but I would leave it for now and try removing it once you have the new build working.

**Comment by dlandon** [comment]
It's a shared memory issue.  Keep increasing the shared memory until you see less that 50% /dev/shm on the Zoneminder console panel.

**Comment by cm86** [comment]
Ok - So now i have the following command running...
`docker run -d --name='Zoneminder' --net='bridge' --privileged=true -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -e 'INSTALL_HOOK'='0' -e 'INSTALL_TINY_YOLOV3'='0' -e 'INSTALL_YOLOV3'='0' -e 'INSTALL_TINY_YOLOV4'='0' -e 'INSTALL_YOLOV4'='0' -e 'INSTALL_FACE'='0' -e 'SHMEM'='25%' -p '8443:443/tcp' -p '9000:9000/tcp' -v '/mnt/user/appdata/Zoneminder':'/config':'rw' -v '/mnt/user/UnraidServer/4TB01/zoneminder/':'/var/cache/zoneminder':'rw,slave' --log-opt max-size=50m --log-opt max-file=1 --shm-size="8G" 'dlandon/zoneminder'`

i've tried it before with an extra variable --> but it didn't work
after adding it to the extra parameter filed it worked...

So this can be closed

Thanks in advance for the quick help...

Chris

**Comment by cm86** [comment]
and now i tested `--privileged=false` 
--> is also working

**Comment by dlandon** [comment]
Remove the old template and use the newest one from the apps.  There were several adjustments.
