### ISSUE TITLE
Temporary failure resolving...

### ISSUE THREAD

**Issue by hitnrun30** [dlandon/zoneminder#149]
Ok, I've followed all the tutorials and such.  no matter what when Zoneminder starts I get Temporary failure resolving 'archive.ubuntu.com' or whatever it wants to update.  I am on a Synology server and followed what was needed it other YT tutorials, but this is ridiculous.  I exec in and set the resolv.conf chmod to 644.  still no good.  I would try to ping but I cant get that installed since it can't get to anywhere.

I have tried everything.  the only thing that is weird is at the beginning of the log there is the line  WARNING: With use-dns(no), dns-cache() will be forced to 'no' too!;  But I even added the --dns value.  at present this is my run command. I even added a script to chmod the resolv.conf

What are my next steps?

docker run -d --name="Zoneminder" \
--net="bridge" \
--privileged="true" \
--restart unless-stopped \
--dns 192.168.1.1 \
-p 8223:80/tcp \
-p 9223:9000/tcp \
-e TZ="America/New_York" \
-e SHMEM="50%" \
-e PUID="1024" \
-e PGID="100" \
-e INSTALL_HOOK="1" \
-e INSTALL_FACE="1" \
-e INSTALL_TINY_YOLO="0" \
-e INSTALL_YOLO="0" \
-e ADVANCED_SCRIPT="1" \
-v "/volume1/docker/zoneminder":"/config":rw \
-v "/volume1/docker/zoneminder/data":"/var/cache/zoneminder":rw \
dlandon/zoneminder:latest

**Comment by dlandon** [comment]
Look at the run command again.  The shared memory configuration is changed.  The SHMEM variable is no longer used.

That warning in the log is a syslog-ng warning and can be ignored.

**Comment by hitnrun30** [comment]
Cool, I will adjust, but I believe the main problem is the network, i switched it to host and there is no problem with it getting the archives and installing.  Why do we need to use bridge anyway?

**Comment by dlandon** [comment]
That shouldn't have anything to do with the updates.  The Bridge mode limits open ports to specific ports, host mode allows all ports.  Unless Host mode is required, Bridge mode offers more security by limiting open ports.

**Comment by hitnrun30** [comment]
Which is fine but i cant connect to the internet with my bridge.  I'm using a synology with the default docker bridge.  I'm happy to create new network connections but have no idea what the values would be.

**Comment by dlandon** [comment]
Just use Host then.

**Comment by hitnrun30** [comment]
I did, but now I get 

(98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80

and Apache won't start.

**Comment by dlandon** [comment]
That's what Host mode does.  It exposes all the ports of the Docker.  Port 80 in the Docker is for http access.

**Comment by hitnrun30** [comment]
so then why won't Apache start?

**Comment by dlandon** [comment]
Port 80 is already in use on that IP address is what that message is telling you.

**Comment by hitnrun30** [comment]
How is that possible if it is within the container and I'm using a totally different external IP.  Here is what I run it with.

docker run -d --name=Zoneminder \
--net=host \
--privileged=true \
--restart unless-stopped \
-p 8223:80/tcp \
-p 9223:9000/tcp \
-e TZ=America/New_York \
-e PUID=1024 \
-e PGID=100 \
-e INSTALL_HOOK=0 \
-e INSTALL_FACE=0 \
-e INSTALL_TINY_YOLO=0 \
-e INSTALL_YOLO=0 \
-v /volume1/docker/zoneminder:/config:rw \
-v /volume1/docker/zoneminder/data:/var/cache/zoneminder:rw \
dlandon/zoneminder:latest

**Comment by PrplHaz4** [comment]
> 
> 
> How is that possible if it is within the container and I'm using a totally different external IP. Here is what I run it with.
> 
> docker run -d --name=Zoneminder
> --net=host
> --privileged=true
> --restart unless-stopped
> -p 8223:80/tcp
> -p 9223:9000/tcp
> -e TZ=America/New_York
> -e PUID=1024
> -e PGID=100
> -e INSTALL_HOOK=0
> -e INSTALL_FACE=0
> -e INSTALL_TINY_YOLO=0
> -e INSTALL_YOLO=0
> -v /volume1/docker/zoneminder:/config:rw
> -v /volume1/docker/zoneminder/data:/var/cache/zoneminder:rw
> dlandon/zoneminder:latest

`--net=host` means the container shares the hosts' network interface - which is likely already using port 80 for the Synology web interface, so zm can't bind to it.  To get around this, you will either need to use `bridge` with the port mappings or change the port the Synology UI listens on.

The port mappings (`-p xxx`) don't do anything when `--net=host`.

I've had your original problem in the past (specifically with this container) where it can't complete the apt-get's at startup - I don't think I ever found a concrete solution, other than deleting my docker networks and trying again later.  Some searching leads to the possibility of rate limiting on the repository side - and it does seem to correlate with the times I've been messing with my containers, but I never got anything concrete....

**Comment by dlandon** [comment]
You will need to get Docker support for your host system.  I can't possibly support all Docker host variants out there.
