### ISSUE TITLE
ONVIF Probe not working

### ISSUE THREAD

**Issue by btnet** [dlandon/zoneminder#15]
I cannot get onvif probe to work when manually probing at the terminal I just get

Name "ZoneMinder::ONVIF::verbose" used only once: possible typo at /usr/bin/zmonvif-probe.pl line 81.
Probing for SOAP 1.1
<Fault xmlns="http://schemas.xmlsoap.org/soap/envelope/"><faultcode>soap:Server</faultcode><faultstring>Error sending / receiving message: Timed out waiting for response</faultstring><faultactor>urn:localhost</faultactor></Fault>
Probing for SOAP 1.2
<Fault xmlns="http://schemas.xmlsoap.org/soap/envelope/"><faultcode>soap:Server</faultcode><faultstring>Error sending / receiving message: Timed out waiting for response</faultstring><faultactor>urn:localhost</faultactor></Fault>

**Comment by dlandon** [comment]
Why don't you use the gui?

**Comment by btnet** [comment]
When I use the GUI no cameras show up

![nocam](https://user-images.githubusercontent.com/11809412/47606469-d7834580-da0b-11e8-9f8b-0e9ecc741cc5.png)

 I presume its because it cannot find any onvif cameras but if I probe a known camera from the terminal I get the following response 

Name "ZoneMinder::ONVIF::verbose" used only once: possible typo at /usr/bin/zmonvif-probe.pl line 81.
ERror  cannot add_IPFilter
ERror  cannot add_ZeroConfiguration
ERror  cannot add_IPVersion6
ERror  cannot add_DynDNS
ERror  cannot add_DiscoveryResolve
ERror  cannot add_DiscoveryBye
ERror  cannot add_RemoteDiscovery
ERror  cannot add_SystemBackup
ERror  cannot add_SystemLogging
ERror  cannot add_FirmwareUpgrade
ERror  cannot add_SupportedVersions
ERror  cannot add_TLS1__1
ERror  cannot add_TLS1__2
ERror  cannot add_OnboardKeyGeneration
ERror  cannot add_AccessPolicyConfig
ERror  cannot add_X__509Token
ERror  cannot add_SAMLToken
ERror  cannot add_KerberosToken
ERror  cannot add_RELToken
Received message:
<GetProfilesResponse xmlns="http://www.onvif.org/ver10/media/wsdl"><Profiles token="MainStreamToken" fixed="true"><Name xmlns="http://www.onvif.org/ver10/schema">MainStream</Name><VideoSourceConfiguration xmlns="http://www.onvif.org/ver10/schema"><Name>videoSourceToken</Name><UseCount>2</UseCount><SourceToken>videoSourceToken</SourceToken><Bounds x="0" y="0" width="1920" height="1080"></Bounds></VideoSourceConfiguration><VideoEncoderConfiguration xmlns="http://www.onvif.org/ver10/schema"><Name>VideoMainEncoder</Name><UseCount>1</UseCount><Encoding>H264</Encoding><Resolution><Width>1920</Width><Height>1080</Height></Resolution><Quality>40</Quality><RateControl><FrameRateLimit>15</FrameRateLimit><EncodingInterval>1</EncodingInterval><BitrateLimit>2150</BitrateLimit></RateControl><H264><GovLength>30</GovLength><H264Profile>Main</H264Profile></H264><Multicast><Address><Type>IPv4</Type><IPv4Address>192.168.5.254</IPv4Address></Address><Port>5544</Port><TTL>300</TTL><AutoStart>false</AutoStart></Multicast><SessionTimeout>PT300S</SessionTimeout></VideoEncoderConfiguration><VideoAnalyticsConfiguration xmlns="http://www.onvif.org/ver10/schema"><Name>VideoAnalyticsToken</Name><UseCount>2</UseCount><AnalyticsEngineConfiguration><AnalyticsModule Name="MyCellMotionModule" Type="tt:CellMotionEngine"><Parameters><SimpleItem Name="Sensitivity" Value="60"></SimpleItem><ElementItem Name="Layout"></ElementItem></Parameters></AnalyticsModule></AnalyticsEngineConfiguration><RuleEngineConfiguration><Rule Name="MyMotionDetectorRule" Type="tt:CellMotionDetector"><Parameters><SimpleItem Name="MinCount" Value="5"></SimpleItem><SimpleItem Name="AlarmOnDelay" Value="100"></SimpleItem><SimpleItem Name="AlarmOffDelay" Value="100"></SimpleItem><SimpleItem Name="ActiveCells" Value="Af/w"></SimpleItem></Parameters></Rule></RuleEngineConfiguration></VideoAnalyticsConfiguration><PTZConfiguration xmlns="http://www.onvif.org/ver10/schema"><Name>ptzToken</Name><UseCount>1</UseCount><NodeToken>ptz_node</NodeToken><DefaultContinuousPanTiltVelocitySpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace</DefaultContinuousPanTiltVelocitySpace><DefaultContinuousZoomVelocitySpace>http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace</DefaultContinuousZoomVelocitySpace><DefaultPTZSpeed><PanTilt x="0.7" y="0.7" space="http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace"></PanTilt><Zoom x="0.7" space="http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace"></Zoom></DefaultPTZSpeed><DefaultPTZTimeout>PT10S</DefaultPTZTimeout></PTZConfiguration></Profiles><Profiles token="SubStreamToken" fixed="true"><Name xmlns="http://www.onvif.org/ver10/schema">SubStream</Name><VideoSourceConfiguration xmlns="http://www.onvif.org/ver10/schema"><Name>videoSourceToken</Name><UseCount>2</UseCount><SourceToken>videoSourceToken</SourceToken><Bounds x="0" y="0" width="1920" height="1080"></Bounds></VideoSourceConfiguration><VideoEncoderConfiguration xmlns="http://www.onvif.org/ver10/schema"><Name>VideoSubEncoder</Name><UseCount>1</UseCount><Encoding>H264</Encoding><Resolution><Width>640</Width><Height>480</Height></Resolution><Quality>40</Quality><RateControl><FrameRateLimit>20</FrameRateLimit><EncodingInterval>1</EncodingInterval><BitrateLimit>696</BitrateLimit></RateControl><H264><GovLength>40</GovLength><H264Profile>Main</H264Profile></H264><Multicast><Address><Type>IPv4</Type><IPv4Address>192.168.5.254</IPv4Address></Address><Port>5544</Port><TTL>300</TTL><AutoStart>false</AutoStart></Multicast><SessionTimeout>PT300S</SessionTimeout></VideoEncoderConfiguration><VideoAnalyticsConfiguration xmlns="http://www.onvif.org/ver10/schema"><Name>VideoAnalyticsToken</Name><UseCount>2</UseCount><AnalyticsEngineConfiguration><AnalyticsModule Name="MyCellMotionModule" Type="tt:CellMotionEngine"><Parameters><SimpleItem Name="Sensitivity" Value="60"></SimpleItem><ElementItem Name="Layout"></ElementItem></Parameters></AnalyticsModule></AnalyticsEngineConfiguration><RuleEngineConfiguration><Rule Name="MyMotionDetectorRule" Type="tt:CellMotionDetector"><Parameters><SimpleItem Name="MinCount" Value="5"></SimpleItem><SimpleItem Name="AlarmOnDelay" Value="100"></SimpleItem><SimpleItem Name="AlarmOffDelay" Value="100"></SimpleItem><SimpleItem Name="ActiveCells" Value="Af/w"></SimpleItem></Parameters></Rule></RuleEngineConfiguration></VideoAnalyticsConfiguration><PTZConfiguration xmlns="http://www.onvif.org/ver10/schema"><Name>ptzToken</Name><UseCount>1</UseCount><NodeToken>ptz_node</NodeToken><DefaultContinuousPanTiltVelocitySpace>http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace</DefaultContinuousPanTiltVelocitySpace><DefaultContinuousZoomVelocitySpace>http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace</DefaultContinuousZoomVelocitySpace><DefaultPTZSpeed><PanTilt x="0.7" y="0.7" space="http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace"></PanTilt><Zoom x="0.7" space="http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace"></Zoom></DefaultPTZSpeed><DefaultPTZTimeout>PT10S</DefaultPTZTimeout></PTZConfiguration></Profiles></GetProfilesResponse>
MainStreamToken, MainStream, H264, 1920, 1080, 15, rtsp://192.168.5.254:5544/live0.264
SubStreamToken, SubStream, H264, 640, 480, 20, rtsp://192.168.5.254:5544/live1.264

**Comment by dlandon** [comment]
This is a Zoneminder issue.  You need to post to the Zoneminder forum for help.
