### ISSUE TITLE
Coral EdgeTPU model path

### ISSUE THREAD

**Issue by artlov** [dlandon/zoneminder#151]
ES and default objectconfig.ini expect Coral EdgeTPU models to be in the /var/lib/zmeventnotification/models/coral_edgetpu folder, but 40_firstrun.sh creating links to /var/lib/zmeventnotification/coral_edgetpu -> /config/hook/coral_edgetpu. May be it would be a good idea to change this path to the default one: /var/lib/zmeventnotification/models/coral_edgetpu -> /config/hook/models/coral_edgetpu?

**Comment by dlandon** [comment]
Looks like it changed in ES 6.1.5.  I'll update it.
