### ISSUE TITLE
Container hangs on 40_firstrun.sh if not connected to internet

### ISSUE THREAD

**Issue by alex28273** [dlandon/zoneminder#153]
Once I have the container setup, I would like to disconnect from the internet (disable through firewall) which is fine until the container needs to be bounced for maintenance (or power failure).

**Comment by dlandon** [comment]
You need an internet connection.  I'm not going to change this,

**Comment by alex28273** [comment]
From a security perspective, that does not make sense to have a security system require connectivity to the internet.

Thank you for the reply.

**Comment by alexyao2015** [comment]
Not only is this a security issue, but this is also poor practice for usage in a container as the app should be fully preinstalled, not installed during runtime...

**Comment by PrplHaz4** [comment]
> 
> 
> Not only is this a security issue, but this is also poor practice for usage in a container as the app should be fully preinstalled, not installed during runtime...

There's other zm images that may fit your use case better - I like that I don't need to run a separate mysql container, and can change included packages by just changing an environment variable and recreating the container...

**Comment by alexyao2015** [comment]
In proper images, that is typically done through the use of tags... You never ever should have the need to have runtime scripts modifying the application itself. Docker takes a different mindset to get used to, but once you learn it properly, its beautiful and resilient.
