### ISSUE TITLE
Bridged network breaks "Probe ONVIF" function

### ISSUE THREAD

**Issue by jeremyenos** [dlandon/zoneminder#155]
Perhaps simply fixed as a caveat in the overview, but maybe this will save someone time that I spent banging my head...  bridged docker networks don't appear to work for the "Probe ONVIF" functionality in adding a camera, due to its dependence on multicast.  I didn't test with --net=host which I suspect would resolve it, but I did use a macvlan network for my Zoneminder docker instance and then my ONVIF probing function worked.

**Comment by dlandon** [comment]
This is not being supported at this time.  We will support this when the funding is raised in GoFundMe for the development and maintenance of a new Docker with ES/ML built in.
