### ISSUE TITLE
container fails to start if no access to the internet

### ISSUE THREAD

**Issue by sebw** [dlandon/zoneminder#157]
I want Zoneminder to sit in a restricted VLAN with no access to the internet.

When I disable access to the internet and start the container, the container fails to start.

`wget -q https://github.com/dlandon/zoneminder/raw/master/zmeventnotification/EventServer.tgz` from the init script gets stuck, which I assume is the culprit.

I suggest `wget -t 10` to reach a timeout faster so the script can resume.

**Comment by dlandon** [comment]
This is not being supported at this time.  We will support this when the funding is raised in GoFundMe for the development and maintenance of a new Docker with ES/ML built in.
