### ISSUE TITLE
Delete monitor 1 API Problem

### ISSUE THREAD

**Issue by ysw0421** [dlandon/zoneminder#16]
Hi, English is not my main language.

We use zoneminder in your dockerhub.

I have been using your hub since version 1.30, but I know it has recently changed to version 1.32.

Delete monitor 1 API   is not working on your images
curl -XDELETE http://server/zm/api/monitors/1.json
![aa](https://user-images.githubusercontent.com/29770142/47615558-bb5ad380-daf3-11e8-93cd-2bd78234c6d0.PNG)

Could you please give me an example to solve the above problem or tell me how to download your old version 1.30?

**Comment by dlandon** [comment]
You can disable api with the Options->System->OPT_USE_API.

**Comment by gwontaeyong** [comment]
Hi @dlandon i'm the coworker with @ysw0421.

we were using your previous version of your zoneminder image.
we run the container with this cmd 'docker run -d 80:80 dlandon/zoneminder'
this version container working well and can use all the APIs.

but after update to v1.31 only Delete API is not working other APIs like a add monitor check monitor are working well and streaming very well.

as you said i turn off the option OPT_USE_API and i trying again but the DELETE API doem't work.

if this error is come from authentication case. 
Maybe the queryLog can't be show up in the output of 'curl -XDELETE http://server/zm/api/monitors/1.json' (https://user-images.githubusercontent.com/29770142/47615558-bb5ad380-daf3-11e8-93cd-2bd78234c6d0.PNG)


i think it's matter of zoneminder auth system or our mistake.
can you guess what is matter of this error.

Thank you.

**Comment by dlandon** [comment]
You should post this on the Zoneminder forum.  It's an issue with Zoneminder and not this docker.

**Comment by gwontaeyong** [comment]
Yes your right @dlandon .
Thank you for checking this. :)
