### ISSUE TITLE
recommended way to upgrade this container?

### ISSUE THREAD

**Issue by Zixim** [dlandon/zoneminder#18]
I'm new to docker, but been using Zoneminder for quite a while.
What is the recommended way to update the container?

In case it makes a difference : this container is running in Openmediavault instead of the _intended_ UnRaid.

**Comment by dlandon** [comment]
I'm not sure how Openmediavault manages dockers, but you should be able to do a docker pull for the latest version.

**Comment by Zixim** [comment]
so, stop the container, pull the latest image, and start the container again ?
