### ISSUE TITLE
 Starting MariaDB database server mysqld    ...fail!

### ISSUE THREAD

**Issue by dmachtey** [dlandon/zoneminder#19]
Hello.
      I'm quite new to docker. but have ran other images with some issues that I was able to fix.
 
      I'm trying to run  dlandon/zoneminder through your docker-run.sh script as root but always get the same errors and then it get closed.  (Bellow the logs)

      How can I solve this?

Best Regards.
DM

Setting shared memory to : 50% of 16294700 bytes
Starting services
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of stop.
/usr/sbin/policy-rc.d returned 101, not running 'stop zoneminder.service'
Detected db service is mysql.service
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory
/usr/sbin/policy-rc.d returned 101, not running 'start mysql.service'
Failed to connect to bus: No such file or directory
NOTE: MySQL/MariaDB not running; please start mysql and run dpkg-reconfigure zoneminder when it is running.
/usr/sbin/policy-rc.d returned 101, not running 'restart zoneminder.service'
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
 * /etc/init.d/mysql: WARNING: /etc/mysql/my.cnf cannot be read. See README.Debian.gz
Jan 31 22:01:26 galacticempire /etc/init.d/mysql[453]: WARNING: /etc/mysql/my.cnf cannot be read. See README.Debian.gz
 * Starting MariaDB database server mysqld
   ...fail!
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Config.pm line 117.
Can't connect to db at /usr/share/perl5/ZoneMinder/Config.pm line 166.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 166.
Compilation failed in require at /usr/bin/zmupdate.pl line 71.
BEGIN failed--compilation aborted at /usr/bin/zmupdate.pl line 71.
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Config.pm line 117.
Can't connect to db at /usr/share/perl5/ZoneMinder/Config.pm line 166.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 166.
Compilation failed in require at /usr/bin/zmupdate.pl line 71.
BEGIN failed--compilation aborted at /usr/bin/zmupdate.pl line 71.
 * Starting Apache httpd web server apache2
 * 
Starting ZoneMinder:
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Config.pm line 117.
Can't connect to db at /usr/share/perl5/ZoneMinder/Config.pm line 166.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder/Config.pm line 166.
Compilation failed in require at /usr/share/perl5/ZoneMinder.pm line 33.
BEGIN failed--compilation aborted at /usr/share/perl5/ZoneMinder.pm line 33.
Compilation failed in require at /usr/bin/zmpkg.pl line 34.
BEGIN failed--compilation aborted at /usr/bin/zmpkg.pl line 34.
ZoneMinder failed to start

*** /etc/my_init.d/40_firstrun.sh failed with status 255

*** Killing all processes...
Jan 31 22:02:06 galacticempire syslog-ng[16]: syslog-ng shutting down; version='3.5.6'

**Comment by nate131** [comment]
I am having this exact same issue. mysql error.log says its permissions based however i see that the permissions have been set just fine. Would this be due to not being run on unRAID?

```
190224  2:59:20 [Note] /usr/sbin/mysqld (mysqld 10.0.38-MariaDB-0ubuntu0.16.04.1) starting as process 587 ...
190224  2:59:20 [Warning] **Can't create test file /var/lib/mysql/a6a0fd115662.lower-test**
190224  2:59:20 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In order to use backoff, increase buffer pool at least up to 20MB.
190224  2:59:20 [Note] InnoDB: Using mutexes to ref count buffer pool pages
190224  2:59:20 [Note] InnoDB: The InnoDB memory heap is disabled
190224  2:59:20 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
190224  2:59:20 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
190224  2:59:20 [Note] InnoDB: Compressed tables use zlib 1.2.8
190224  2:59:20 [Note] InnoDB: Using Linux native AIO
190224  2:59:20 [Note] InnoDB: Using CPU crc32 instructions
190224  2:59:20 [Note] InnoDB: Initializing buffer pool, size = 128.0M
190224  2:59:20 [Note] InnoDB: Completed initialization of buffer pool
**190224  2:59:20 [ERROR] InnoDB: ./ibdata1 can't be opened in read-write mode**
190224  2:59:20 [ERROR] InnoDB: The system tablespace must be writable!
190224  2:59:20 [ERROR] Plugin 'InnoDB' init function returned error.
190224  2:59:20 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
190224  2:59:20 [ERROR] mysqld: File '/var/lib/mysql/aria_log_control' not found (Errcode: 13 "Permission denied")
190224  2:59:20 [ERROR] mysqld: Got error 'Can't open file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
190224  2:59:20 [ERROR] Plugin 'Aria' init function returned error.
190224  2:59:20 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
190224  2:59:20 [Note] Plugin 'FEEDBACK' is disabled.
190224  2:59:20 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
190224  2:59:20 [ERROR] Unknown/unsupported storage engine: InnoDB
190224  2:59:20 [ERROR] Aborting
190224  2:59:20 [Note] /usr/sbin/mysqld: Shutdown complete
```

**Comment by dlandon** [comment]
Where do you have these volumes mapped?
-v "/mnt/cache/appdata/Zoneminder":"/config":rw \
-v "/mnt/cache/appdata/Zoneminder/data":"/var/cache/zoneminder":rw \

These are Unraid specific and would need to be changed for your system,.

**Comment by nate131** [comment]
same location - they exist on the host in /mnt/cache/appdata/Zoneminder and exist in the container as /config and /var/cache/zoneminder for the .../data volume

**Comment by Novotech-Busse** [comment]
Hi, is there a solution for this ? 

im using the :latest tag as today.

the log says:

```
Setting shared memory to : 50% of 3901824 bytes
Starting services...
 * Starting MariaDB database server mysqld                                                                                                 [fail]
DBI connect('database=zm;host=localhost','zmuser',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at /usr/share/perl5/ZoneMinder/Config.pm line 117.
```

the mysql log says:

```91110  4:35:09 [Note] InnoDB: Initializing buffer pool, size = 128.0M
191110  4:35:09 [Note] InnoDB: Completed initialization of buffer pool
191110  4:35:09 [ERROR] InnoDB: ./ibdata1 can't be opened in read-write mode
191110  4:35:09 [ERROR] InnoDB: The system tablespace must be writable!
191110  4:35:09 [ERROR] Plugin 'InnoDB' init function returned error.
191110  4:35:09 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
191110  4:35:09 [ERROR] mysqld: File '/var/lib/mysql/aria_log_control' not found (Errcode: 13 "Permission denied")
191110  4:35:09 [ERROR] mysqld: Got error 'Can't open file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
191110  4:35:09 [ERROR] Plugin 'Aria' init function returned error.
191110  4:35:09 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
191110  4:35:09 [Note] Plugin 'FEEDBACK' is disabled.
191110  4:35:09 [ERROR] Can't open the mysql.plugin table. Please run mysql_upgrade to create it.
191110  4:35:09 [ERROR] Unknown/unsupported storage engine: InnoDB
191110  4:35:09 [ERROR] Aborting```

ive tried to fix the permission but that did not work. If i start the container with 

docker run -it Zoneminder /bin/bash

and then start the /etc/my_init.d/40_....sh it seems to work. any ideas ?

**Comment by elsieej** [comment]
have anyone fixed this issues ?
