### ISSUE TITLE
Containers are atomic

### ISSUE THREAD

**Issue by autonomy-rocks** [dlandon/zoneminder#200]
This means containers should not install updates when starting. Or ever.

This is not how containers are supposed to be used, and leads to problems. Not to mention a slow startup time because the updates aren't persisted when the container restarts, and the updates run all over again when the container starts. Every. Single. Time.

If security updates should be applied to the container, then a new container should be built and published to the docker hub, so that users can update to the latest version of the container. This is how containers are intended to be used. Not like a VM where data is expected to be persisted across reboots.

**Comment by alexyao2015** [comment]
@tstivers1990 https://github.com/zoneminder-containers/zoneminder-base

**Comment by tstivers1990** [comment]
> @tstivers1990 https://github.com/zoneminder-containers/zoneminder-base

What about it?

**Comment by sgofferj** [comment]
@tstivers1990 Even if you are right with regards to the facts, I don't think there is any justification to be that abrasive. @dlandon has spent a lot of time to make zoneminder available as a container. He didn't ask anything for it in return. If you don't like his way to do it (which also frustrated me a few times in the past), don't use his images. If you think you can do it better, do it better. But being abrasive doesn't server any purpose other than creating a negative atmosphere.
