### ISSUE TITLE
chown root:www-data on /var/cache/zoneminder

### ISSUE THREAD

**Issue by wvxx** [dlandon/zoneminder#22]
Hi there,

I've setup a container using your image and migrated my previous installation to it (db + recordings). Now, whenever I restart my container ownership gets changed to root:www-data on zoneminder folders making it no longer writable to apache's www-data (on my previous installation those folders were www-data:www-data owned).

I tried adjusting these settings in init/40_firstrun.sh and rebuilding the image after that, but for some reason this makes apache refuse connections. There are no error messages in container log nor apache's error log. Restarting apache results in [fail], though when I check its status it says it is running.

I'm a docker dummy, just started familiarizing myself with it recently so I guess I must be doing something wrong here. I'll be grateful for any assistance.
Thanks in advance!

**Comment by dlandon** [comment]
Read the read.me about starting Zoneminder.  The following environment variables set the file permissions:
-e PUID="99" 
-e PGID="100"

**Comment by wvxx** [comment]
Thanks for responding. Which readme are you referring to? I could not find anything related in your repository's readme.

What I tried doing is changing those variables to www-data (33), unfortunately it did not resolve- the issue as www-data is still unable to write to these directories.
Thanks.
