### ISSUE TITLE
hook feature testing

### ISSUE THREAD

**Issue by erikomv** [dlandon/zoneminder#25]
I use your latest container with OpenMediaVault. Running stable for nearly 6 months now.
Thanks a lot for providing it.

The eventnotification server without hooks works well with my setup.
Testing the hook feature I followed your instructions on the unraid forum.
A bit of feedback:

1) It looks like the "detect.py" is not copied into the docker on startup, only the "detect_wrapper.sh" is.

2) I am struggeling with the line `python setup.py install` in the "userscript.sh" because it gives the `python: can't open file 'setup.py': [Errno 2] No such file or directory` error.
Do I have to copy the file "setup.py" into the appdata/zoneminder/hook directory as well to be copied into the container at startup? I am sure I am missing something here but cant figure out what myself.
The first lines of the "userscript.sh" are excecuted ok and dependencies install without errors in the log.

Thanks for looking into this.

**Comment by dlandon** [comment]
Follow the documentation here: https://github.com/pliablepixels/zmeventnotification

I've done most of the work.  You should only have to install some modules and then let the docker copy your hook files and go.

**Comment by erikomv** [comment]
I read the documentation a couple of times. 
I also installed the hook feature inside your container the manual way as per pliablepixels guide to gain more insight. And the object detection worked. 
But its not persistent, so not really the way to go I think.

I will read the documentation again as suggested and let you know.

**Comment by dlandon** [comment]
You should not have to do anything but provide the userscript.sh to install the additional modules and supply your scripts in the /config/hook/ folder.  The setup has already been done and should work.

**Comment by erikomv** [comment]
After some more testing and reading and installing I would conclude with two issues as feedback:

1) detect.py does not get copied into the container.
	--> I think that could be fixed by modifying the 40_firstrun.sh, line 76 by omitting the underline (aka "_").

2) Installation of the helper python modules in pliablepixels/zmeventnotification/hook/zmes_hook_helpers inside the container did not work for me.
My workaround is to create the folder **zmes_hook_helpers** with associated *.py files in the /config/hook folder. Also I copied the setup.py script into the /config/hook folder and modified the corresponding line in userscript.sh to point at the setup.py script, like this : `python /config/hook/setup.py install`. That way all helper modules registered and object detection works like a charm now. Yay!
But of course it would be much better to have the container setup take care of that.

If you need more information/ testing please let me know. If not the issue can be closed from my point of view.
And thanks a lot for your speedy replies.

**Comment by dlandon** [comment]
1. I can fix this.

2. The zmeventnotification hook is not used by everyone and I don't want to add more modules to an already bloated docker.  With the use of the userscript.sh, you can install the modules needed and make other modifications as necessary.

**Comment by dlandon** [comment]
I've just changed the docker so you can set an environment variable 'INSTALL_HOOK="1"' and the hook modules will be loaded and the 'setup.py' run inside the docker.

**Comment by erikomv** [comment]
Latest container version installed flawlessly for me.
Exactly the implementation I had hoped for (with the ability to choose if face recognition should be installed).

Kudos to you.
