### ISSUE TITLE
change the ip of the database

### ISSUE THREAD

**Issue by juanmoura** [dlandon/zoneminder#27]
Is there any way to change the ip of the database inside the docker run script?
I currently have to configure zm.conf and insert it into the volume /mnt/cache/appdata/Zoneminder/appdata/conf/zm.conf

I ask why I saw other images in dockerhub have this method of changing the port in the docker run.

**Comment by dlandon** [comment]
That is the way Zoneminder is set up to work.  I don't have any plans to make any changes to the Docker.  Why is this a problem?
