### ISSUE TITLE
turn on MQTT?

### ISSUE THREAD

**Issue by moore66982** [dlandon/zoneminder#29]
Have the container running fine, appears to work, but want to turn on MQTT to send events to home assistant, have tried modifying zmeventnotification.ini to 

# Use MQTT for messaging (default: no)
[mqtt]
enable = yes

But in restarting the container, its not picked up. 

How can I turn on mqtt?

**Comment by dlandon** [comment]
Which .ini file are you modifying?  It has to be the one in config.  Not the default configuration ini.

**Comment by moore66982** [comment]
modified   /mnt/cache/appdata/Zoneminder/zmeventnotification.ini previously
found a read.me in mnt/cache/appdata/Zoneminder/conf in there I see instructions, but nothing about mqtt.

**Comment by moore66982** [comment]
already have mosquitto running on the same machine, any way to tell ZM/Event Server to use that?

**Comment by dlandon** [comment]
Your best bet is to look at the zmeventmonitor documentation here: https://zmeventnotification.readthedocs.io/en/latest/guides/install.html
