### ISSUE TITLE
yolov3 and tinyyolo folders empty

### ISSUE THREAD

**Issue by arturol76** [dlandon/zoneminder#32]
Hi,
the docker runs smoothly (i.e. zoneminder works and zmeventnotification seems to be ok as well). 

However, looking at looking at https://zmeventnotification.readthedocs.io/en/latest/guides/hooks.html, I would expect to find models in the following folders:
/var/lib/zmeventnotification/models/yolov3
/var/lib/zmeventnotification/models/tinyyolo 
...while such folders are empty. Is that ok? 

What about detect.py and detect_wrapper.sh? Shouldn't they be in /usr/bin?
And objectconfig.ini in /etc/zm?

Thanks.
Arturo.

**Comment by dlandon** [comment]
You put the files in the respective /appdata/zoneminder/ folders and they are copied into the docker image when it is started.

Read about it here: https://forums.unraid.net/topic/56632-support-dlandon-zoneminder-132/?tab=comments#comment-554524

**Comment by dlandon** [comment]
The latest update of the docker will install those files and setup for hook processing.
