### ISSUE TITLE
ZM docker build (not just unraid)

### ISSUE THREAD

**Issue by pliablepixels** [dlandon/zoneminder#33]
Hi, would you be interested in tweaking this repo to become an official ZM docker build? This is  the only one I know of that makes it easy to get ZM+ES+ML working. I just built it for my mac and with some small tweaks, everything seems to work well. If you think its something you want to help us with (i.e. take this and make it an official ZM docker build for the full package), would be great if you could join the ZM slack channel to chat about it. I spoke about this briefly to @connortechnology as well and it looks interesting. If not, no worries - great work!

**Comment by dlandon** [comment]
I would be interested  What would it take to make it an official docker?

**Comment by dlandon** [comment]
How do I join the ZM slack channel?

**Comment by pliablepixels** [comment]
[link to join](https://join.slack.com/t/zoneminder-chat/shared_invite/enQtNTU0NDkxMDM5NDQwLTlhZDU2MGU4MmZmN2MxOTg1MmNmNmZjZGRmY2EzMThhNGQ0MWNmZTg1ZmYzNDQ4YjliMzVmYTQ3MDc5MTkzODE)
