### ISSUE TITLE
Publish a build with master tag for the latest

### ISSUE THREAD

**Issue by danlsgiga** [dlandon/zoneminder#36]
There are a huge amount of fixes in the zoneminder master builds. Can you build one with the `:master` tags by using `ppa:iconnor/zoneminder-master`

**Comment by dlandon** [comment]
Already did that,  Search for it.

**Comment by danlsgiga** [comment]
Would you mind pointing me in the right direction then? Because I can't see any build or tags in https://hub.docker.com/r/dlandon/zoneminder/tags that have `master` on it.
Thanks

**Comment by PrplHaz4** [comment]
for posterity...
https://github.com/dlandon/zoneminder.master-docker
https://hub.docker.com/r/dlandon/zoneminder.master
`dlandon/zoneminder.master`
