### ISSUE TITLE
 No module named 'future'

### ISSUE THREAD

**Issue by bonon** [dlandon/zoneminder#39]
after issuing : sudo -u www-data /mnt/Zoneminder/hook/detect_wrapper.sh
i get this error:

```
Traceback (most recent call last):
  File "/mnt/Zoneminder/hook/detect.py", line 21, in <module>
    import zmes_hook_helpers.utils as utils
  File "/usr/local/lib/python3.6/dist-packages/zmes_hook_helpers/utils.py", line 20, in <module>
    from future import standard_library
ModuleNotFoundError: No module named 'future'

```

pip install future doesnt work (pip3 either)

**Comment by dlandon** [comment]
Be sure you are using the latest docker image.

**Comment by bonon** [comment]
i pulled it yesterday so guess its the latest

**Comment by dlandon** [comment]
Be sure you set the INSTALL_HOOK="1" environment variable to load all the hook modules.  Read the description for more details.

**Comment by bonon** [comment]
just double checked it. im 100% sure i set it to 1. did all according to your description. Step by step still this occur

**Comment by dlandon** [comment]
Review the docker log and you should see the installation of the hook processing modules.
