### ISSUE TITLE
Question: SSMTP working?

### ISSUE THREAD

**Issue by ngodfriedt** [dlandon/zoneminder#4]
Hi,

I've spend days on getting smtp working in your docker, but I can't get it to work. Does it work for you? From command line ssmtp works, but not from within ZoneMinder.

Regards,

Niels

**Comment by dlandon** [comment]
It works.  Follow this guide:  https://wiki.zoneminder.com/How_to_get_ssmtp_working_with_Zoneminder

**Comment by ngodfriedt** [comment]
I have followed the guide and read all forum posts of ssmtp, but can't get it to work. But thanks, now at least I know it is not in the docker image.
