### ISSUE TITLE
privileged, and bridge network

### ISSUE THREAD

**Issue by tbowmo** [dlandon/zoneminder#41]
Why do you recommend starting the container with a bridged network, and in privileged mode?

In my opinion you should stay away from privileged containers as much as possible.

**Comment by dlandon** [comment]
I agree about the privileged mode, but I ran into an issue where Zoneminder would have an problem without it.  I can't remember the what it was though.  You can run it any way you like.

The bridge mode limits port access to only those defined.  Makes sense to me.
