### ISSUE TITLE
zmEventNotifications don't seem to work

### ISSUE THREAD

**Issue by phdelodder** [dlandon/zoneminder#43]
I installed you docker container and noticed that there are a few things that need to be change.

1.  zmeventnotification.ini, set the hook to /config/hook/zm_detect_wrapper.sh
2.  zm_detect_wrapper.sh, change DETECTION_SCRIPT to /config/hook/zm_detect.py
3.  chmod +x /config/hook/zm_detect.py
4.  objectconfig.ini, set secrets to /config/secrets

After that there where no more errors still it wasn't working as intended, no mqtt, no feedback on the object detected. 

```
Nov 28 21:25:28 b08b327f22a0 zmeventnotification[760]: INF [New event 60 reported for Monitor:1 (Name:Oprit) ]
Nov 28 21:25:28 b08b327f22a0 zmeventnotification[1575]: INF [Forking process:1575 to handle 1 alarms]
Nov 28 21:25:28 b08b327f22a0 zmeventnotification[1575]: INF [processAlarms: EID:60 Monitor:Oprit (id):1 cause:]
Nov 28 21:25:28 b08b327f22a0 zmeventnotification[1575]: INF [Invoking hook:'/config/hook/zm_detect_wrapper.sh' 60 1 "Oprit" ""]
Nov 28 21:25:28 b08b327f22a0 /zm_detect.py[1579]: INF [zmesdetect_m1] [---------| app version: 4.6.1 |------------]
Nov 28 21:25:29 b08b327f22a0 zmeventnotification[1575]: INF [For Monitor:1 event:60, hook script returned with text: exit:1]
Nov 28 21:25:29 b08b327f22a0 zmeventnotification[1575]: INF [Ending process:1575 to handle alarms]
```

**Comment by phdelodder** [comment]
I assume the exit 1 is coming from the fact that nothing is being detected.

**Comment by dlandon** [comment]
The new version of zmeventnotification has renamed some files.  Check out the zmeventnotification documentation and make the ini changes as necessary.  The secrets.ini is used for your credentials.  It is at /config/secrets.ini so it is persistent.
