### ISSUE TITLE
path broken after 4.6 event server update

### ISSUE THREAD

**Issue by luxflow** [dlandon/zoneminder#44]
it seems after upgrading 4.6 event server, paths are broken in multiple points

according to this commit https://github.com/dlandon/zoneminder/commit/8abbd690c2a1acafe1769eac3a529f45fbcd4a98, file names are changed
/root/zmeventnotification/detect_wrapper.sh -> /root/zmeventnotification/zm_detect_wrapper.sh  
/root/zmeventnotification/detect.py -> /root/zmeventnotification/zm_detect.py
right?

1) two old files(detect_wrapper.sh, detect.py) are not removed although they are not used at all
https://github.com/dlandon/zoneminder/tree/8abbd690c2a1acafe1769eac3a529f45fbcd4a98/zmeventnotification

2) symlink old files not new one
https://github.com/dlandon/zoneminder/blob/8abbd690c2a1acafe1769eac3a529f45fbcd4a98/init/40_firstrun.sh#L335

3) accessing non exist files
there are no /var/lib/zmeventnotification/bin/zm_detect_wrapper.sh
 /var/lib/zmeventnotification/bin/zm_detect.py
should be symlinked first at 2) + chmod +x
https://github.com/dlandon/zoneminder/blob/8abbd690c2a1acafe1769eac3a529f45fbcd4a98/zmeventnotification/zmeventnotification.ini#L112
https://github.com/dlandon/zoneminder/blob/8abbd690c2a1acafe1769eac3a529f45fbcd4a98/zmeventnotification/zm_detect_wrapper.sh#L22

4) also this path should be fixed
there is no file /etc/zm/secrets.ini 
should be symlinked first
https://github.com/dlandon/zoneminder/blob/master/zmeventnotification/objectconfig.ini#L11
or should use /config/secrets.ini like this one
https://github.com/dlandon/zoneminder/blob/master/zmeventnotification/zmeventnotification.ini#L7

**Comment by dlandon** [comment]
Fixed in latest update.
