### ISSUE TITLE
zm_detect.py path in zm_detect_wrapper.sh 

### ISSUE THREAD

**Issue by kjake** [dlandon/zoneminder#45]
zm_detect_wrapper.sh calls /var/lib/zmeventnotification/bin/zm_detect.py, a path that doesn't exist. A soft link could be added to /config/hook, or the path changed to just /config/hook - not sure what makes the most sense. Also, these zm_detect* files overwrite my modifications each time I pull a new docker image.

**Comment by dlandon** [comment]
The paths have been fixed it the latest release.,

The zm_detect files will overwrite your existing files because they change on each update of zmeventnotification.  You really shouldn't have to change them from the defaults.
