### ISSUE TITLE
Explosive Memory Usage

### ISSUE THREAD

**Issue by joshstrange** [dlandon/zoneminder#46]
I don't think I've changed anything at all about how this container runs but recently I've noticed it is just chewing up ram (like 20GB). When I restart the container it will fall then slowly build back up. I'm wondering if anyone else is experiencing this issue and/or if there is some way to mitigate it?

**Comment by dlandon** [comment]
Your docker is probably mis-configured and writing in the docker image.

**Comment by joshstrange** [comment]
Just to clarify, my docker image isn't filling up but my ram is. Here is the config for my docker container. Is there a mount point I'm missing?

![Screenshot 2019-12-20 09 35 36](https://user-images.githubusercontent.com/462796/71261734-21b04000-230c-11ea-8d33-64687414477b.png)

**Comment by dlandon** [comment]
Check your data path.  You are mapping to a share 'Zoneminder'.  If that share does not exist, you will be writing to tmpfs which is in ram.
