### ISSUE TITLE
Im sorry if i do wront but im new to this

### ISSUE THREAD

**Issue by ClabbeBula** [dlandon/zoneminder#47]
Is it only me who only get 
For Monitor:5 event:187, hook script returned with text: exit:1

When I use this docker..
It newer identifies any object or write back to zm.. The only thing i can see in Events is "Motion All"

It has never ever marked a person or car or anything?

I start the docker with "sudo docker start Zoneminder"

Should I do something else?

**Comment by dlandon** [comment]
You aren't starting the docker properly.  Use the docker-run.sh script or docker-compose.yaml.

**Comment by ClabbeBula** [comment]
Im maybe wrong..
But I have already started it with docker-run.sh with "1" instead of zeros..
So zoneminder work, if I do a sudo docker start Zoneminder..
but not 

if i run...
docker run -d --name="Zoneminder" \
--net="bridge" \
--privileged="true" \
-p 8443:443/tcp \
-p 9000:9000/tcp \
-e TZ="Europe/Stockholm" \
-e SHMEM="50%" \
-e PUID="99" \
-e PGID="100" \
-e INSTALL_HOOK="1" \
-e INSTALL_FACE="1" \
-e INSTALL_TINY_YOLO="1" \
-e INSTALL_YOLO="1" \
-v "/mnt/Zoneminder":"/config":rw \
-v "/mnt/Zoneminder/data":"/var/cache/zoneminder":rw \
dlandon/zoneminder

it just says that I have a docker zoneminder in conflict

**Comment by ClabbeBula** [comment]
![7D00A212-1F61-4437-86A2-1843BF282DC0](https://user-images.githubusercontent.com/59126655/71315590-829d5c80-2461-11ea-8764-fb73e08cc353.jpeg)
![D2AFB7CF-6142-49D6-83A6-4983FB456219](https://user-images.githubusercontent.com/59126655/71315591-8335f300-2461-11ea-9800-ed0eca06fd2c.jpeg)

As pictures the cameras just have events for motion.

But i dont know if there was a object.


And the log days exit:1

And in this specific case it was a car and 2 people in the clip

**Comment by dlandon** [comment]
I can't support the hook operation of Zoneminder.  I build the Docker and will support any Docker issues.  You will have to get support on the Zoneminder forums.

**Comment by ClabbeBula** [comment]
Ok thanks anyway. And its a very good docker. Thanks alot.
Just wonder if it was only me?

Have a merry christmas!
