### ISSUE TITLE
Apache2 Ubuntu Default Page

### ISSUE THREAD

**Issue by novarx** [dlandon/zoneminder#48]
Hey Dan,

Since Today I'm getting just the _Apache2 Ubuntu Default Page_ when starting a brand new Container.

So I pulled this Repo and did ```docker-compose up```, when visiting _https://localhost:8443/_ there is just the _Default Page_.
Am I missing to set a Property or has something changed?

I tested it on _Docker for Windows_ and also on an _Ubuntu_ machine.
It worked on another Ubuntu, where I had the Commit _ed764bf30c2ce483ab009b097736dce7f4a7e077_, maybe that helps.

Best regards

**Comment by dlandon** [comment]
You have the wrong url.  Read the README.

**Comment by witchdr** [comment]
For others that find this page because we didn't read the [README](https://github.com/dlandon/zoneminder#usage), you need to go to https://localhost:8443/zm or http://localhost:8080/zm if using the documented values.
