### ISSUE TITLE
Question: User running the image

### ISSUE THREAD

**Issue by ngodfriedt** [dlandon/zoneminder#5]
Hi, 

I've got another question for you. I'm still trying to get ssmtp in ZoneMinder to work. It seems to something specific to setup of the docker. I can't see any log of zmfilter after turning debugging on. Can you tell me with what user you are running the image? Is it a dedicated user for the image with maybe special priviliges or do you run it under the root user?

Thanks in advance!

Regards,

Niels

**Comment by dlandon** [comment]
The Zoneminder installation is a standard installation and is running as a service.  I would assume root user.

**Comment by ngodfriedt** [comment]
I mean the docker image itself (running on UnRaid I think in your case)

**Comment by dlandon** [comment]
Root user.

**Comment by ngodfriedt** [comment]
Ok, maybe that's the reason then that ssmtp doesn't work for me. Thanks for your answer. Now I've got another lead to follow.
