### ISSUE TITLE
Permission help

### ISSUE THREAD

**Issue by yvessa** [dlandon/zoneminder#50]
Hello,

I'm pretty new to this docker and docker in general. Sorry if it's a newbie question.

I have been playing with this docker for few hours. Usually I don't have issue with permission but I must have missed something.

Here is my docker-compose file :
  zoneminder:
    image: dlandon/zoneminder:latest
    container_name: zoneminder
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/zoneminder:/config:rw
      - ${USERDIR}/docker/zoneminder/data:/var/cache/zoneminder:rw
      - /mnt/ryzen7-10tb/smb-share-ryzen7/cam/zoneminder:/video:rw
    ports:
        - 7443:443/tcp
        - 9500:9000/tcp
    network_mode: "bridge"
    privileged: true
    environment:
      - PUID=1000
      - PGID=999    
      - TZ=${TZ}
      - SHMEM=50%
      - INSTALL_HOOK=0
      - INSTALL_FACE=0
      - INSTALL_TINY_YOLO=0
      - INSTALL_YOLO=0

I created my folders with PUID = 1000 and PGID = 999.

Here is one error in my log right after I log in the web gui.

_Cannot write to content dirs('/var/cache/zoneminder/events','/var/cache/zoneminder/images'). Check that these exist and are owned by the web account user_

Any tips?

Regards and merry xmas all!

Yves

**Comment by dlandon** [comment]
Get into the docker and verify that the ownership and permissions are:
drwxrwxrwx 2 root www-data 6 Dec 25 13:45 cache
drwxrwxrwx 2 root www-data 6 Dec 25 13:45 events
drwxrwxrwx 2 root www-data 6 Dec 25 13:45 images
drwxrwxrwx 2 root www-data 6 Dec 25 13:45 temp

**Comment by yvessa** [comment]
Yes these folders had these permissions

yves@ryzen7:~/docker/zoneminder/data$ ls -la
total 24
drwxrwxr-x+ 6 yves docker   4096 déc 25 12:50 .
drwxrwxr-x+ 9 yves docker   4096 déc 25 12:50 ..
drwxrwxrwx+ 2 root www-data 4096 déc 25 12:50 cache
drwxrwxrwx+ 2 root www-data 4096 déc 25 12:50 events
drwxrwxrwx+ 2 root www-data 4096 déc 25 12:50 images
drwxrwxrwx+ 2 root www-data 4096 déc 25 12:50 temp

**Comment by dlandon** [comment]
I would use the default permissions:
PUID="99"
PGID="100"

**Comment by yvessa** [comment]
It works when I move the zoneminder folders path below a parent folder with a group = my user name. And also only using default PUID/PGID. I let the script creating these folders during docker creation.

When the parent folder group = docker, it does not work. Usually I put all my docker config files within a docker folder. And that folder has a group = docker.

I guest the script to make directory does not handle specific user/group and also need a parent folder with a group = "user name".

Thank you for your support, @dlandon
