### ISSUE TITLE
Manual start of zmeventnotification.pl

### ISSUE THREAD

**Issue by jakobeissler** [dlandon/zoneminder#51]
I've executed the image like this:

```
docker run -d --name="Zoneminder" \
--net="bridge" \
--privileged="true" \
-p 8443:443/tcp \
-p 9001:9000/tcp \
-e TZ="America/Santiago" \
-e SHMEM="50%" \
-e PUID="99" \
-e PGID="100" \
-e INSTALL_HOOK="1" \
-e INSTALL_FACE="1" \
-e INSTALL_TINY_YOLO="1" \
-e INSTALL_YOLO="1" \
-v "/mnt/Zoneminder":"/config":rw \
-v "/mnt/Zoneminder/data":"/var/cache/zoneminder":rw \
dlandon/zoneminder
```

It is working as expected but i have to enter container on every restart and execute the following command manually, otherwise it won't work:

`sudo -u www-data /usr/bin/zmeventnotification.pl --config /etc/zm/zmeventnotification.ini`

What am i missing?

**Comment by dlandon** [comment]
You shouldn't have to do that.  What is in the docker log?

**Comment by jakobeissler** [comment]
Well i deletedthe container and ran it again... it is working now. I guess i missed something the first time. I'm closing this one.

Thank you!!!
