### ISSUE TITLE
Use of detection and face recognition

### ISSUE THREAD

**Issue by OrkhanHI** [dlandon/zoneminder#52]
Hi,

Thank you for awesome repo. I managed to run everything smoothly and can access ZM console and see my camera feeds. 

For detection and face recognition part could you please provide comprehensive documentation how to do that, because by changing some **.ini** files I did not get anything to work.

Thank you in advance.

**Comment by dlandon** [comment]
https://zmeventnotification.readthedocs.io/en/stable/
