### ISSUE TITLE
After upgrade, phone gets notifications for _all_ motion events

### ISSUE THREAD

**Issue by nolanl** [dlandon/zoneminder#53]
not just motion events that have a object detected.

I have:
"detect_pattern=(person)" in objectconfig.ini, which worked fine for months before this update.

I guess the upgrade from zmeventnotification 4.6 -> 5.4 broke something.

**Comment by dlandon** [comment]
There are a lot of changes in 5.4 and you will have to use the default .ini and reconfigure.  Check documentation [here](https://zmeventnotification.readthedocs.io/en/stable/)

**Comment by nolanl** [comment]
Thanks.
