### ISSUE TITLE
image versioning

### ISSUE THREAD

**Issue by der-andrew** [dlandon/zoneminder#54]
Please, consider to implement versioning of docker images. By DB version for example. It's very important for multiple (50+) installations. I'd like to be sure all of my further installations have the same database version as previouse ones.

P.S. latest in production is not best practise as well)

**Comment by dlandon** [comment]
This is not something I will consider.  You should consider building your own Docker that meets your requirements.  Asking me to invest time that I don't get paid for, in an effort to support your 50+ installations, that I'm sure you get paid for, is rather annoying.

**Comment by der-andrew** [comment]
Ops...
The greatest answer that I've ever had.
No pay - no gain.
Cool!!!

Sorry for annoying. It's not what I meant.
