### ISSUE TITLE
latest docker build getting php error

### ISSUE THREAD

**Issue by faspina** [dlandon/zoneminder#57]
This is where it bombs out after re-start. I also deleted the image and re-pulled. This happened suddenly today . It looks like a problem with  /etc/my_init.d/20_apt_update.sh

Setting up php7.4-fpm (7.4.2-2+ubuntu18.04.1+deb.sury.org+1) ...
Setting up php7.4-fpm (7.4.2-2+ubuntu18.04.1+deb.sury.org+1) ...
update-alternatives: error: alternative path /run/php/php7.4-fpm.sock doesn't exist
dpkg: error processing package php7.4-fpm (--configure):
installed php7.4-fpm package post-installation script subprocess returned error exit status 2
Setting up libapache2-mod-php7.4 (7.4.2-2+ubuntu18.04.1+deb.sury.org+1) ...
libapache2-mod-php7.4: not switching MPM - already enabled
Feb 1 06:59:32 5f1438c9b5dc libapache2-mod-php7.4: libapache2-mod-php7.4: not switching MPM - already enabled
Setting up php7.4 (7.4.2-2+ubuntu18.04.1+deb.sury.org+1) ...
Processing triggers for systemd (237-3ubuntu10.33) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Processing triggers for php7.4-cli (7.4.2-2+ubuntu18.04.1+deb.sury.org+1) ...
Processing triggers for php7.4-cli (7.4.2-2+ubuntu18.04.1+deb.sury.org+1) ...
Processing triggers for libapache2-mod-php7.4 (7.4.2-2+ubuntu18.04.1+deb.sury.org+1) ...
Errors were encountered while processing:
php7.4-fpm
E: Sub-process /usr/bin/dpkg returned an error code (1)
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up php7.4-fpm (7.4.2-2+ubuntu18.04.1+deb.sury.org+1) ...
update-alternatives: error: alternative path /run/php/php7.4-fpm.sock doesn't exist
dpkg: error processing package php7.4-fpm (--configure):
installed php7.4-fpm package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
php7.4-fpm
E: Sub-process /usr/bin/dpkg returned an error code (1)
*** /etc/my_init.d/20_apt_update.sh failed with status 100

**Comment by tevd** [comment]
Exact same issue here, so this appears to be a problem with the docker build and not some invalid configuration.

**Comment by faspina** [comment]
Trying to build the docker myself , its does not like php version 7.4, tried it with 7.3 but no luck either

**Comment by faspina** [comment]
failing on this command in dockerfile

sudo apt-get -y install php7.4 php7.4-fpm libapache2-mod-php7.4 php7.4-mysql php7.4-gd

E: Unable to locate package php7.4
E: Couldn't find any package by glob 'php7.4'
E: Couldn't find any package by regex 'php7.4'
E: Unable to locate package php7.4-fpm
E: Couldn't find any package by glob 'php7.4-fpm'
E: Couldn't find any package by regex 'php7.4-fpm'
E: Unable to locate package libapache2-mod-php7.4
E: Couldn't find any package by glob 'libapache2-mod-php7.4'
E: Couldn't find any package by regex 'libapache2-mod-php7.4'
E: Unable to locate package php7.4-mysql
E: Couldn't find any package by glob 'php7.4-mysql'
E: Couldn't find any package by regex 'php7.4-mysql'
E: Unable to locate package php7.4-gd
E: Couldn't find any package by glob 'php7.4-gd'
E: Couldn't find any package by regex 'php7.4-gd'

**Comment by sic79** [comment]
I have exactly the same issue. Though I had corrupted my docker first.

**Comment by faspina** [comment]
Its got to be a php7.4 repo issue

**Comment by tix5000** [comment]
Receiving same php error as described above

**Comment by faspina** [comment]
I cloned the repo, change the PHP version to 7.1 at the top , that was the last change to the dockerfile in the last update.  
I rebuilt the container locally  and tagged it ,  change my unraid template to pull from my new tag. Now zoneminder is working fine.  I guess 7.4 no longer exist.  

this line:  PHP_VERS="7.1"

I am checking PHP 7.2 now. 7.3 did not work

**Comment by dlandon** [comment]
It just worked for me - php 7.4.

**Comment by faspina** [comment]
Yep, just tried it again, it appears to be working now with 7.4 . Weird

**Comment by dlandon** [comment]
Momentary repository issue that got solved.
