### ISSUE TITLE
Restart every X time

### ISSUE THREAD

**Issue by phdelodder** [dlandon/zoneminder#6]
I have add an export of the log. It seems that everything is crashing after a X amount of time, and I can't seem to pin point what the problem is. 

[zm-log.txt](https://github.com/dlandon/zoneminder/files/1386304/zm-log.txt)

**Comment by dlandon** [comment]
You should look at addressing the buffer overrun issue to start.

**Comment by phdelodder** [comment]
How can I adres the buffer overrun, do you have any pointers?

**Comment by dlandon** [comment]
Try increasing the shared memory.
