### ISSUE TITLE
/dev/shm: 100%

### ISSUE THREAD

**Issue by NXT-4** [dlandon/zoneminder#62]
Hi,

Is it possible to increase the RAM of the docker container? I can’t add more camera’s because the /dev/shm: 100% is at maximum.

Thanks.

**Comment by dlandon** [comment]
100% SHM is 100% of system memory.  Add more system memory.

**Comment by NXT-4** [comment]
How do I do that? I’m running it on a Synology NAS with 16 GB of ram.

**Comment by NXT-4** [comment]
Do I have to do it with a command line?

**Comment by dlandon** [comment]
I don't know how Synology manages memory.

**Comment by dlandon** [comment]
You might be over committing SHM memory so there is not enough memory left.  Cut it back to 50% ans start from there.
