### ISSUE TITLE
Move Apache/PHP Log file to /config

### ISSUE THREAD

**Issue by djamp42** [dlandon/zoneminder#63]
I'm pretty new to Docker so I'm sorry if i'm going about this wrong. 

I am using this docker container, before this container i have a NGINX reverse proxy with fail2ban. Most other docker containers will keep the log files in the /config directory so they can be easily imported into my NGINX reverse proxy docker.

This docker container doesn't do that so i was just hoping this could be changed. 

Thanks again for the container it works pretty well other then this small issue. 

The main directory to move would be /var/log/apache2, but i guess any other log files would be helpful too.

**Comment by dlandon** [comment]
Create a script /config/userscript.sh with the following content:
`#!/bin/bash
#
mkdir -p /config/logs
rm -rf /var/log/syslog
ln -sf /config/log/syslog /var/log/syslog
`
Restart the docker and the syslog will now be written at /config/logs/.  This script runs when the docker is started.
