### ISSUE TITLE
CRON CMD hourly

### ISSUE THREAD

**Issue by jcdex69** [dlandon/zoneminder#68]
Hi, 

Thanks for your works, i have a problem/bug ?

I follow your guide and just change setting in config like this :

sudo docker run -d --name="Zoneminder" \
--net="bridge" \
--privileged="true" \
-p 8443:443/tcp \
-p 9000:9000/tcp \
-e TZ="France/Paris" \
-e SHMEM="50%" \
-e PUID="99" \
-e PGID="100" \
-e INSTALL_HOOK="1" \
-e INSTALL_FACE="1" \
-e INSTALL_TINY_YOLO="1" \
-e INSTALL_YOLO="1" \
-v "/mnt/Zoneminder":"/config":rw \
-v "/mnt/Zoneminder/data":"/var/cache/zoneminder":rw \
dlandon/zoneminder

i watch the status with the command docker logs -f Zoneminder

Since one day its turn in loop i have the impression (screen attach)

![zoneminder](https://user-images.githubusercontent.com/6523358/75325286-dae54600-5878-11ea-9309-e7fe056852a1.png)

Thanks you for your help and sorry for my english

**Comment by dlandon** [comment]
That's normal.  It's not in a loop.

**Comment by jcdex69** [comment]
Ok, thx, so i must wait or do anythink ?

**Comment by dlandon** [comment]
No.  It is normal and that's just the hourly cron logging.  Nothing to worry about.
