### ISSUE TITLE
QUESTION: Mount disk

### ISSUE THREAD

**Issue by joselito11** [dlandon/zoneminder#69]
How to correct mount an external/internal disk to ZM in docker for saving events? My install is the same as in read me, just another ports and time. Have tried to mount, but get always: Path do not exist. Must be ZM reinstalled with mount volumes or can it be done with mounting and permissions?

**Comment by dlandon** [comment]
It sounds like you are not mapping the volumes correctly.  Be sure the external mounts exist.

**Comment by joselito11** [comment]
Thanks, have it now.

**Comment by joselito11** [comment]
Thanks, have it now. But with a catch. After system reboot, I must always in docker mount volume, I have it set in fstab in host and container. How to get it auto mount persistent?

**Comment by dlandon** [comment]
I don't know because I have no idea what you are hosting the docker on.  It's not a docker issue.  Look at the host.

**Comment by joselito11** [comment]
Debian Buster stable. The host is automounting drive after restart, but docker wont. What should I look in host? I want Zoneminder to save events on seconf internal disk. Or shoul I reinstall and change:` -v "/mnt/Zoneminder":"/config":rw \` to: `-v "/media/zm":"/config":rw \`-my mounted second disk.
