### ISSUE TITLE
Startup script checking for updates.

### ISSUE THREAD

**Issue by ycodryn** [dlandon/zoneminder#70]
When docker is down and is no internet connection, at startup it will not boot because packages are not updating. This feature in my opinion should be enabled or disabled by env.

**Comment by dlandon** [comment]
The idea is to update for security and update Zoneminder when it is updated.  I don't want to make it optional.  People will turn it off and never update.

**Comment by dlandon** [comment]
You can stop the updates by this command:

`rm /etc/my_init.d/20_apt_update.sh`

**Comment by ycodryn** [comment]
Ty for that command. The idea behind this was that after my nas made a scheduled restart but because of a dns issue , zoneminder had no connection to internet and because of this docker did not start, none of my cameras could start any record on zm, so I had aprox 8h without any security. As I said was just an idea.

**Comment by ycodryn** [comment]
Another idea @dlandon if you can is to allow the container to start even if the update is not successful. This way zoneminder can update itself when it can but start any way when it can`t.

**Comment by dlandon** [comment]
Fixed in next release.
