### ISSUE TITLE
CRON HOURLY since 24h

### ISSUE THREAD

**Issue by jcdex69** [dlandon/zoneminder#71]
hello, thank you for your response in my other request but can you tell me more ? should i wait or do something specific ? 
thank you so much

![CRON](https://user-images.githubusercontent.com/6523358/75366912-c2e4e500-58bf-11ea-8cbe-34dd1902f95b.png)

**Comment by jcdex69** [comment]
PS : I forgot to tell you i can't access to the zm https://mylocalip:8443/zm/ 
http error 500

**Comment by dlandon** [comment]
The CRON logging is normal.  It doesn't mean anything.

> PS : I forgot to tell you i can't access to the zm https://mylocalip:8443/zm/
http error 500

This isn't enough information for me to help you.  What are your port mappings?

**Comment by jcdex69** [comment]
Hello, Thx for your response, 

8443:443/tcp 

I apply this config : 

sudo docker run -d --name="Zoneminder" \
--net="bridge" \
--privileged="true" \
-p 8443:443/tcp \
-p 9000:9000/tcp \
-e TZ="France/Paris" \
-e SHMEM="50%" \
-e PUID="99" \
-e PGID="100" \
-e INSTALL_HOOK="1" \
-e INSTALL_FACE="1" \
-e INSTALL_TINY_YOLO="1" \
-e INSTALL_YOLO="1" \
-v "/mnt/Zoneminder":"/config":rw \
-v "/mnt/Zoneminder/data":"/var/cache/zoneminder":rw \
dlandon/zoneminder

PS: With your default config in another Vm it's work fine.

**Comment by dlandon** [comment]
It's the VM setup.  Try https://mylocalip/zm/.

**Comment by jcdex69** [comment]
not working :( 

with :  https://mylocalip/zm/ = nothing (ERR_CONNECTION_REFUSED)
with :  https://mylocalip:8443/zm/ = HTTP ERROR 500

**Comment by jcdex69** [comment]
Ps : If i go to https://mylocalip:8443 I have Apache2 Ubuntu Default Page

**Comment by dlandon** [comment]
Look at the docker log.  I think you might have a msql issue.

Please move this issue to the Zoneminder forum https://forums.zoneminder.com/

**Comment by jcdex69** [comment]
Thx, I change the config like this and setup new vm and it's work :

sudo docker run -d --name="Zoneminder" \
--net="bridge" \
--privileged="true" \
-p 8443:443/tcp \
-p 9000:9000/tcp \
-e TZ="America/New_York" \
-e SHMEM="50%" \
-e PUID="99" \
-e PGID="100" \
-e INSTALL_HOOK="1" \
-e INSTALL_FACE="1" \
-e INSTALL_TINY_YOLO="1" \
-e INSTALL_YOLO="1" \
-v "/mnt/Zoneminder":"/config":rw \
-v "/mnt/Zoneminder/data":"/var/cache/zoneminder":rw \
dlandon/zoneminder
