### ISSUE TITLE
Support for multi-port

### ISSUE THREAD

**Issue by dseven** [dlandon/zoneminder#72]
Support for multi-port, as described [here](https://medium.com/zmninja/multi-port-storage-areas-and-more-d5836a336c93), would be good. For now, I'm hacking around it with a userscript.sh containing this kludge, but it's a bit fragile (e.g. if the default apache config changes):

```
#!/bin/bash

MPORT_START=9001
MPORT_END=9009

ORIG_VHOST="_default_:443"

NEW_VHOST=${ORIG_VHOST}
PORT=${MPORT_START}
while [[ ${PORT} -le ${MPORT_END} ]]; do
    egrep -sq "Listen ${PORT}" /etc/apache2/ports.conf || echo "Listen ${PORT}" >> /etc/apache2/ports.conf
    NEW_VHOST="${NEW_VHOST} _default_:${PORT}"
    PORT=$(($PORT + 1))
done

perl -pi -e "s/${ORIG_VHOST}/${NEW_VHOST}/ if (/<VirtualHost/);" /etc/apache2/sites-enabled/default-ssl.conf

service apache2 restart
```

Envisaging somewhere like environment variables to specify the port range, and better code than above to effect it in the apache config.

**Comment by dlandon** [comment]
What is it you are trying to accomplsh?

**Comment by dseven** [comment]
I'm using zmNinjaPro to monitor cameras. Without multi-port support, you don't get an actual video stream - rather a snapshot every X seconds (where X defaults to 2, with a minimum of 1). With multi-port enabled, you get a decently-smooth stream. It's described on the linked page.

**Comment by dlandon** [comment]
I'll have to think about this.

**Comment by F2FG** [comment]
It is not directly related to dsever request but it may be useful. I use Home Assistant (https://www.home-assistant.io/) and its mobile app to monitor my zonemider camera streams. Home Assistant has a ZoneMinder module built-in: https://www.home-assistant.io/integrations/zoneminder/

In Home Assistant main view the streams are thumbnails that refresh every 10 seconds, but if I click on a stream thumbnail I can view the regular stream (in my case mjpeg, 5 fps).

**Comment by dlandon** [comment]
A new docker is building that implements multi-port support.  Define two environment variables:

MULTI_PORT_START="9001"
MULTI_PORT_END="9009"
