### ISSUE TITLE
Montage review - All events = blank white page

### ISSUE THREAD

**Issue by F2FG** [dlandon/zoneminder#74]
Hello, when I click on _Montage review_, then _All events_, I get a blank white page.

If I click on _8 hours_ it works, but if I manually extend the review period over 48 hours using the calendars I get a blank white page.

I made a few more tests and I found out something that may be interesting. If I visit this web address:

https://MY-IP-ADDRESS/zm/?view=montagereview&fit=1&minTime=2020-03-02 17:12:**55**&maxTime=2020-03-04 17:13:09&live=0&scale=1&speed=1

it works. Notice that the starting seconds (in bold) are 55.

If I visit this web address:

https://MY-IP-ADDRESS/zm/?view=montagereview&fit=1&minTime=2020-03-02 17:12:**56**&maxTime=2020-03-04 17:13:09&live=0&scale=1&speed=1

I get the blank white page. Notice that the starting seconds (in bold) are 56.

One second difference triggers this behavior.

Do you have any suggestions to further debug this issue?

Thank you very much

Giacomo

**Comment by dlandon** [comment]
This is a Zoneminder issue.  Please go to the ZM forum for support.
