### ISSUE TITLE
Problem with face training procedure

### ISSUE THREAD

**Issue by mimahome** [dlandon/zoneminder#75]
Dear all,

I face a problem when executing the face training procedure. Please cf. the output below.

I am running ZoneMinder v1.34.5. I have already double-checked everything in the docs. Face detection package works when using in python3. Object recogniton works fine.

Is this still a configuration issue?

Your help is very much appreciated.

Thanks,
Markus

>> sudo -u www-data /var/lib/zmeventnotification/bin/zm_train_faces.py
Traceback (most recent call last):
File "/var/lib/zmeventnotification/bin/zm_train_faces.py", line 2, in <module>
import zmes_hook_helpers.face_train as train
File "/usr/local/lib/python3.6/dist-packages/zmes_hook_helpers/face_train.py", line 18, in <module>
g.logger.debug(
AttributeError: 'NoneType' object has no attribute 'debug'

**Comment by dlandon** [comment]
Looks to be a ZM issue.  Go to the Zoneminder forum for help.
