### ISSUE TITLE
Changelog.md

### ISSUE THREAD

**Issue by roondar** [dlandon/zoneminder#76]
Hello,

As you have a few releases, it should be more readable to move the changelog in dedicate file instead of the README.md ? 

What do you think ? 

And great work by the way. 👍

**Comment by connortechnology** [comment]
We havn't been maintaining CHANGELOG.md.  Since we do our changelogs in github, I think we should delete CHANGELOG.md.  

Although if we ever decided to leave github, it might be better to have it.

**Comment by dlandon** [comment]
Done.

**Comment by roondar** [comment]
Nice :+1:
