### ISSUE TITLE
/etc/init.d/mysql: ERROR: The partition with /var/lib/mysql is too full!

### ISSUE THREAD

**Issue by worm6666** [dlandon/zoneminder#78]
after few days of running well on windows under docker - it always stops working after restart

it cannot be started anymore - because of "/var/lib/mysql is too full!"

is there option how to clear this ?

it cannot be started - also it cannot be repaired from within of the container...

I have also connected another storage and put all events to there to not to fill up base virtual file system - but it not helps...

**Comment by murlifhstp** [comment]
Hey, same problem here - docker on ubuntu 18.04.

The directory /var/lib/mysql is a link to /config/mysql  

> ls -la /var/lib/mysql
> lrwxrwxrwx 1 mysql mysql 13 Mar 28 15:48 /var/lib/mysql -> /config/mysql

Maybe there is a problem in the firstrun.sh script because if I try to start mysql manual it works.
(created a new image after the first run error)

> $ docker run -it -v "/media/daten/bat_cctv/config":"/config":rw -v >"/media/daten/bat_cctv/data":"/var/cache/zoneminder":rw murli_zoneminder /bin/bash
> root@c0a314d2059b:/#
> root@c0a314d2059b:/# /etc/init.d/mysql start
 > * Starting MariaDB database server mysqld                                                                                                                                                                                              > [ OK ]
> root@c0a314d2059b:/# /etc/init.d/mysql status
> * /usr/bin/mysqladmin  Ver 9.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu on x86_64
> Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.
> 
> Server version          10.1.44-MariaDB-0ubuntu0.18.04.1
> Protocol version        10
> Connection              Localhost via UNIX socket
> UNIX socket             /var/run/mysqld/mysqld.sock
> Uptime:                 6 sec
> 
> Threads: 1  Questions: 61  Slow queries: 0  Opens: 32  Flush tables: 1  Open tables: 26  Queries per second avg: 10.166

**Comment by worm6666** [comment]
I'm little lost in Your answer - can You explain more what You did ? I cannot enter into the corrupted container anymore because it exits immediately after the error is shown in log and the container stops... thanks.

**Comment by murlifhstp** [comment]
Sorry the post before was addressed at the maintainer for further investigation.
But in the meantime I got the container working - I figured out that the privileged Option in the docker run command is the problem (for me) - without this option the container works for me.
@dlandon: For which function does the container need this option - GPU support?

`docker run -d --name="Zoneminder" 
--net="bridge" 
`**--privileged="true"** `
-p 8443:443/tcp 
-p 9000:9000/tcp 
-e TZ="America/New_York" 
-e SHMEM="50%" 
-e PUID="99" 
-e PGID="100" 
-e INSTALL_HOOK="0" 
-e INSTALL_FACE="0" 
-e INSTALL_TINY_YOLO="0"
-e INSTALL_YOLO="0" 
-e MULTI_PORT_START="0" 
-e MULTI_PORT_END="0" 
-v "/mnt/Zoneminder":"/config":rw 
-v "/mnt/Zoneminder/data":"/var/cache/zoneminder":rw 
dlandon/zoneminder`

If you want to start an interactive shell in the container use this command (easier than in the post before):
`docker run **-it** --name="Zoneminder" --net="bridge" -p 8443:443/tcp -p 9000:9000/tcp -e TZ="Europe/Vienna" -e SHMEM="50%" -e PUID="99" -e PGID="100" -e INSTALL_HOOK="0" -e INSTALL_FACE="0" -e INSTALL_TINY_YOLO="0" -e INSTALL_YOLO="0" -v "XXXXXXXXXXXX/config":"/config":rw -v "XXXXX/data":"/var/cache/zoneminder":rw dlandon/zoneminder /bin/bash   `
The` /bin/bash` overrides the `CMD` in the docker file und the `-it `starts the container interactive mode. To start the whole startup script for zoneminder - use the original CMD from the dockerfile: `/sbin/my_init`

Now the container doesn't stops after an error and stays in the shell.

**Comment by dlandon** [comment]
I don't remember.  I believe it has always been that way.

**Comment by dlandon** [comment]
Just ran a test and on my system if priviledged is off, my cameras don't work.  Looks like it is system dependent.

**Comment by murlifhstp** [comment]
My cameras are connected over RTSP. In this configuration - I think my system don't need access to the hardware - so it works for me without priviledged mode.

Any ideas why mysql didn't start with this option?

My host system:
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:24:19 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

**Comment by worm6666** [comment]
omitted **--privileged="true"** for now, will report later what happens after few days of running with camera ON

[have created short guide for configuration transfer/backup:](https://forums.zoneminder.com/viewtopic.php?f=36&t=26600#p114659)

**Comment by worm6666** [comment]
and, again, after few days running container, same error... this sucks... :(

**Comment by dlandon** [comment]
You need to look at the host system.  This is not a common problem and has not been reported on Unraid systems.  You might consider using a separate mysql docker.

**Comment by worm6666** [comment]
I have it only for ZoneMinder - only for Your image... Nothing else... Perhaps it is alone problem of Windows version of Docker - the right way is probably to use Docker and Your image on LINUX on bare metal - I have created one already on one notebook - it works nice without the MYSQL FULL problem... Will see if it doesn't fires such problem after a while - but probably not - the storage is from start up equal the size of space on /dev/sda2 - now it is 45(55)G used of 219G space - and works well with thousands of events... I test the auto-delete parameter older than "-X day" - hope it works... but the used space is little confusing...
![2020-04-09_11-06-43](https://user-images.githubusercontent.com/8425192/78879114-c093b000-7a53-11ea-8bba-1f00f32f880a.jpg)
![2020-04-09_11-01-38_firefox](https://user-images.githubusercontent.com/8425192/78879123-c5586400-7a53-11ea-9bd3-7657a619d81d.jpg)

**Comment by sebastianberm** [comment]
I have this problem as well. I've attempted to fix it by entering the container, as @murlifhstp suggested. Furthermore I've manually modified the 40_... bash file. 
It might be due to the fact I'm using unionfs for the /config. This seems to be posing all kinds of issues. 
I guess it might be an idea to disable any further exotic configurations.
After I did that, it was working correctly :-)

**Comment by worm6666** [comment]
@sebastianberm - how do You changed the 40_... bash file (and which one) please ? do You have snapshot before and after please ? thank You.
