### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by jeevans207** [dlandon/zoneminder#8]
Every couple of days i see that zoneminder is unavailable. I see "MySQL server has gone away" as a fatal error in the log. Restarting the docker temp fixes it. Any help is appreciated!

**Comment by dlandon** [comment]
What environment are you running the Docker?  unRAID?  Check the log and see if there is anything else going on that would affect the MySQL server.  I suspect you are running out of memory.

**Comment by jeevans207** [comment]
I am running docker in unraid.  I was on version 6.3.5 until today.  I upgraded to unraid 6.4.1.  With some further investigation, I agree it may be related to memory.  looks like zoneminder MySQL was crashing when mover was running nightly.  Post upgrade, I manually ran mover once and zoneminder survived.  I will see what happens over the next few days.

**Comment by dlandon** [comment]
The default of 50% shared memory is probably too much.  Try cutting that down to 30%.  You do this in the advanced settings in the Docker template.
