### ISSUE TITLE
Bogus docker compose file (\t in it)

### ISSUE THREAD

**Issue by Faless** [dlandon/zoneminder#82]
There are 2 tabs in the docker compose file as can be seen (shown in red) in github file viewer:
https://github.com/dlandon/zoneminder/blob/7c686c05225fdf8e0e14490da72fecc752c6f9db/docker-compose.yaml#L20-L25

This cause:
```
ERROR: yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "./docker-compose.yaml", line 21, column 1
```

When trying to run it.

**Comment by thobaier** [comment]
Fixed in https://github.com/dlandon/zoneminder/pull/85 and now in master branch available.
