### ISSUE TITLE
Fails Due to "exec format error"

### ISSUE THREAD

**Issue by deltoss** [dlandon/zoneminder#87]
Nice project, would be awesome to set up Zoneminder via docker without making your own docker image.

I'm trying to run the image `dlandon/zoneminder` on my Raspberry Pi 4, using the latest Raspbian OS at time of writing.

When I follow the standard install procedures, where I run the below command:

```bash
docker run -d --name="Zoneminder" \
--net="bridge" \
--privileged="true" \
-p 8443:443/tcp \
-p 9000:9000/tcp \
-e TZ="America/New_York" \
-e SHMEM="50%" \
-e PUID="99" \
-e PGID="100" \
-e INSTALL_HOOK="0" \
-e INSTALL_FACE="0" \
-e INSTALL_TINY_YOLO="0" \
-e INSTALL_YOLO="0" \
-e MULTI_PORT_START="0" \
-e MULTI_PORT_END="0" \
-v "/mnt/Zoneminder":"/config":rw \
-v "/mnt/Zoneminder/data":"/var/cache/zoneminder":rw \
dlandon/zoneminder
```

My docker container exits with status of 1. When I dig up the logs using the command `docker logs Zoneminder`, the error I see is:
```bash
standard_init_linux.go:211: exec user process caused "exec format error"
```

Does anyone have an idea what this issue could be about?

**Comment by deltoss** [comment]
Perhaps the issue is this, where the Raspberry Pi 4 uses ARM architecture.
https://stackoverflow.com/questions/52767983/docker-error-standard-init-linux-go185-exec-user-process-caused-exec-format-e

**Comment by deltoss** [comment]
At a closer look, looks like the base image used was `phusion/baseimage`, which at time of writing, only supports:
* amd64
* arm64
* arm

**Comment by deltoss** [comment]
Tested the `phusion/baseimage` image, using different versions & tags, just doing a basic hello world image.

Turns out:
* `0.11` doesn't work since it only supports amd64. This is the version this project is currently using.
   ![image](https://user-images.githubusercontent.com/9282390/78612651-34478880-78ad-11ea-8695-e1c3bd4a73af.png)
* `master` works fine on the Raspberry Pi 4, as it has a multi-architecture feature where it supports the CPU architecture I mentioned above (i.e. amd64, arm64, arm).

So in conclusion, some approach to solve the issue, if I want to use Docker is:
1. Make a PR to this project to change it to use `phusion/baseimage:master` instead of `phusion/baseimage:0.11`.
2. Fork this project, change the docker file to use the `phusion/baseimage:master` instead of `phusion/baseimage:0.11`. Push my own version of the image to dockerhub, and use that image.
3. I can build an image from scratch and change it to a different base image instead of using `phusion/baseimage` (Not sure if this is a lot of work).

**Comment by deltoss** [comment]
@dlandon, What do you think of the prospects of approach 01 above?

**Comment by dlandon** [comment]
This docker was created to primarily support Unraid.  It is available for other systems, but that is not a primary goal.  I have no interest in changing the baseimage on a docker that is working for many thousands of users and having to offer support for the issues that will come up.  I have no interest in supporting arm systems.  You should fork this work and create your own docker.

**Comment by deltoss** [comment]
That's very unfortunate, you probably want to put that information on the docs to avoid confusion then.

**Comment by Vispen74** [comment]
> That's very unfortunate, you probably want to put that information on the docs to avoid confusion then.
> 
> Didn't think just upgrading the version of the base image is a big change. Guess I'll make my fork and try it on my end.

Did you make a fork? Would you mind share it? Need this for ARM or ARM64 as well.

**Comment by deltoss** [comment]
I gave up on Zoneminder.
I instead switched to Shinobi and made my own docker fork of their official one (to support ARM).

https://github.com/deltoss/ShinobiDocker

**Comment by gador** [comment]
@Vispen74 and for everyone interested in a working arm fork:
Due to the change commit [cce59f1](https://github.com/dlandon/zoneminder/commit/cce59f1d51e1c6997ad3994eba9539abb923f0cd) the base image changed to 
```
phusion/baseimage:bionic-1.0.0
```
which builds on arm64. To actually use this zoneminder docker image, it needs to be build for arm64 (since only amd64 arch is hosted on docker hub for this repo). 
To do so, i simply cloned this repo and issued
```
docker build -t self/zoneminder:latest -t self/zoneminder:1.34 .
```
In the cloned directory on my raspberry pi (note I tag my builds with "self"). Now, you can simply follow the instructions for zoneminder in the repo with docker run, but replace the image with "self/zoneminder" (or however you taged the build).

Hope it helps.
