### ISSUE TITLE
Failed to build dlib

### ISSUE THREAD

**Issue by peste19** [dlandon/zoneminder#89]
I am trying to run the initial setup and I am getting this error, any help to get passed this would be appreciated

> Failed to build dlib
> 
> here is the error log
> 
> [ 83%] Linking CXX static library libdlib.a
> 
> [ 83%] Built target dlib
> 
> Scanning dependencies of target dlib_python
> 
> [ 83%] Building CXX object CMakeFiles/dlib_python.dir/src/dlib.cpp.o
> 
> [ 84%] Building CXX object CMakeFiles/dlib_python.dir/src/matrix.cpp.o
> 
> [ 84%] Building CXX object CMakeFiles/dlib_python.dir/src/vector.cpp.o
> 
> [ 85%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_c_trainer.cpp.o
> 
> [ 86%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_rank_trainer.cpp.o
> 
> [ 86%] Building CXX object CMakeFiles/dlib_python.dir/src/decision_functions.cpp.o
> 
> [ 87%] Building CXX object CMakeFiles/dlib_python.dir/src/other.cpp.o
> 
> [ 88%] Building CXX object CMakeFiles/dlib_python.dir/src/basic.cpp.o
> 
> [ 88%] Building CXX object CMakeFiles/dlib_python.dir/src/cca.cpp.o
> 
> [ 89%] Building CXX object CMakeFiles/dlib_python.dir/src/sequence_segmenter.cpp.o
> 
> [ 90%] Building CXX object CMakeFiles/dlib_python.dir/src/svm_struct.cpp.o
> 
> [ 90%] Building CXX object CMakeFiles/dlib_python.dir/src/image.cpp.o
> 
> In file included from /tmp/pip-build-vz6571cp/dlib/dlib/../dlib/image_transforms.h:21:0,
> 
> from /tmp/pip-build-vz6571cp/dlib/tools/python/src/image.cpp:6:
> 
> /tmp/pip-build-vz6571cp/dlib/dlib/../dlib/image_transforms/label_connected_blobs.h: In function ‘long unsigned int dlib::label_connected_blobs(const image_type&, const background_functor_type&, const neighbors_functor_type&, const connected_functor_type&, label_image_type&) [with image_type = dlib::numpy_image<long unsigned int>; label_image_type = dlib::numpy_image<unsigned int>; background_functor_type = dlib::zero_pixels_are_background; neighbors_functor_type = dlib::neighbors_24; connected_functor_type = dlib::connected_if_both_not_zero]’:
> 
> /tmp/pip-build-vz6571cp/dlib/dlib/../dlib/image_transforms/label_connected_blobs.h:132:19: internal compiler error: Segmentation fault
> 
> unsigned long label_connected_blobs (
> 
> ^~~~~~~~~~~~~~~~~~~~~
> 
> Please submit a full bug report,
> 
> with preprocessed source if appropriate.
> 
> See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
> 
> CMakeFiles/dlib_python.dir/build.make:326: recipe for target 'CMakeFiles/dlib_python.dir/src/image.cpp.o' failed
> 
> make[2]: *** [CMakeFiles/dlib_python.dir/src/image.cpp.o] Error 1
> 
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_python.dir/all' failed
> 
> make[1]: *** [CMakeFiles/dlib_python.dir/all] Error 2
> 
> Makefile:83: recipe for target 'all' failed
> 
> Failed building wheel for dlib
> 
> make: *** [all] Error 2
> 
> Traceback (most recent call last):
> 
> File "<string>", line 1, in <module>
> 
> File "/tmp/pip-build-vz6571cp/dlib/setup.py", line 261, in <module>
> 
> 'Topic :: Software Development',
> 
> File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
> 
> return distutils.core.setup(**attrs)
> 
> File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
> 
> dist.run_commands()
> 
> File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
> 
> self.run_command(cmd)
> 
> File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
> 
> cmd_obj.run()
> 
> File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
> 
> self.run_command('build')
> 
> File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
> 
> self.distribution.run_command(command)
> 
> File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
> 
> self.run_command(cmd_name)
> 
> File "/tmp/pip-build-vz6571cp/dlib/setup.py", line 135, in run
> 
> self.build_extension(ext)
> 
> File "/tmp/pip-build-vz6571cp/dlib/setup.py", line 175, in build_extension
> 
> subprocess.check_call(cmake_build, cwd=build_folder)
> 
> File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
> 
> raise CalledProcessError(retcode, cmd)
> 
> subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j1']' returned non-zero exit status 2.

**Comment by dlandon** [comment]
I have no dea what you are talking about here.
