### ISSUE TITLE
Allow opt out of apt updates

### ISSUE THREAD

**Issue by RandomGHUser** [dlandon/zoneminder#92]
Having the container automatically search, download, and install the same updated ubuntu packages every time it is created can be a nuisance and time waster on slower connections.   It would be beneficial if you could add an environment variable to opt out of checking for updates on container creation. 

I can hack around it by modifying/removing your 20_apt_update.sh script in my_init.d, but it would be easier to only have to set a variable on container start.

**Comment by dlandon** [comment]
It is important that Ubuntu security updates be applied.  ZM is also updated at the same time.  Security updates are not a waste of time.  Sounds like you need a faster Interenet connection.
