### ISSUE TITLE
shm stuck at 64M on synology docker (and filled 100%)

### ISSUE THREAD

**Issue by bonjour81** [dlandon/zoneminder#94]
Hi,
I try to make zoneminder work on my synology docker.
If I understood correctly, SHM size should be 50% of allowed memory, but it seems stuck to default value (64m).

```
root@dlandon-zoneminder1:/# df -h                                                                                                                                                       
Filesystem      Size  Used Avail Use% Mounted on                                                                                                                                        
/dev/vg1000/lv  3.5T  1.5T  2.1T  43% /                                                                                                                                                 
tmpfs            64M     0   64M   0% /dev                                                                                                                                              
tmpfs           4.8G     0  4.8G   0% /sys/fs/cgroup                                                                                                                                    
/dev/vg1000/lv  3.5T  1.5T  2.1T  43% /config                                                                                                                                           
shm              64M   64M     0 100% /dev/shm                                                                                                                                          
tmpfs           4.8G     0  4.8G   0% /proc/asound                                                                                                                                      
tmpfs           4.8G     0  4.8G   0% /proc/acpi                                                                                                                                        
tmpfs           4.8G     0  4.8G   0% /proc/scsi                                                                                                                                        
tmpfs           4.8G     0  4.8G   0% /sys/firmware    
```                                                                                                                                 

my synology as 10G of RAM.
I tried to setup the docker either with or without memory restriction (as proposed by synology interface when launching the docker).

it's a fresh install from today (latest), so zoneminder v1.34

**Comment by dlandon** [comment]
Did you set the SHM environment variable?

**Comment by Iruberiam** [comment]
set shm_size to 512m or more.

**Comment by connortechnology** [comment]
I'm having this issue as well.  ENV vars SHMEM is 50% and SHM is 4096.  (Trying out different things). Neither env var seems to be having any effect.

**Comment by dlandon** [comment]
I wonder if the host is limiting the available memory to the docker and requestng 50% is getting a small amount of memory.

**Comment by dlandon** [comment]
This is the command to set the shm tmpfs.

`mount -t tmpfs -o rw,nosuid,nodev,noexec,relatime,size=${SHMEM} tmpfs /dev/shm`

The size is supposed to be a percentage of /proc/meminfo.

Whst does /proc/meminfo show as available memory?

**Comment by connortechnology** [comment]
So I believe the issue here is that the container was not created in permissive mode.  (When creating it, go to advanced settings -> Device and check Permissive mode).  When not in permissive mode you can't mount /dev/shm to the right size (You get permission denied).

**Comment by Juggler00** [comment]
> So I believe the issue here is that the container was not created in permissive mode. (When creating it, go to advanced settings -> Device and check Permissive mode). When not in permissive mode you can't mount /dev/shm to the right size (You get permission denied).

I tried adding `privileged: true` to my docker-compose.yaml, but `/dev/shm` remains at 64M.

**Comment by kabadisha** [comment]
I had the same issue. I had to add the following argument to the run command:
`--shm-size="512m"`

**Comment by dlandon** [comment]
There is a new docker available that should fix this.  Look at the updated docker run for an adjustment in /dev/shm.
