### ISSUE TITLE
Having a lot of trouble writing to mounted shares

### ISSUE THREAD

**Issue by Wheresitat** [dlandon/zoneminder#95]
Hello,

Great job on putting this container together, i have no trouble writing to the database or pictures / video when i write to the default container locations however when i try to change my config location or the event storage location to a share on my Windows box or a NAS i get the following errors:

May 12 16:01:02 2d51022e229d zmc_m3[958]: ERR [zmc_m3] [Can't mkdir /zoneminder/3: Permission denied],
May 12 16:01:05 2d51022e229d zma_m2[954]: ERR [zma_m2] [Can't mkdir /zoneminder/2: Permission denied],
May 12 16:01:05 2d51022e229d zmdc[908]: INF [Starting pending process, zma -m 3],
May 12 16:01:05 2d51022e229d zma_m2[954]: ERR [zma_m2] [Can't mkdir /zoneminder/2/2020-05-12: No such file or directory],
May 12 16:01:05 2d51022e229d zma_m2[954]: ERR [zma_m2] [Can't mkdir /zoneminder/2/2020-05-12/4267: No such file or directory],

I am able to browse to these locations from the Zoneminder container and can write to them manually.

I have mounted the shares via fstab and my other containers have no trouble writing to them.
Here is my docker script:

docker run -d --name="Zoneminder" \
--net="bridge" \
--privileged="true" \
-p 443:443/tcp \
-p 85:80/tcp \
-p 9002:9002/tcp \
-e TZ="Australia/Sydney" \
-e SHMEM="50%" \
-e PUID="1001" \
-e PGID="1001" \
-e INSTALL_HOOK="0" \
-e INSTALL_FACE="0" \
-e INSTALL_TINY_YOLO="0" \
-e INSTALL_YOLO="0" \
-e MULTI_PORT_START="0" \
-e MULTI_PORT_END="0" \
-v "/mnt/Zoneminder":"/config":rw \
-v "/media/nvrdata":"/zoneminder":rw \
dlandon/zoneminder

And here is what my fstab looks like for that mounted share:

//192.168.1.7/nvrdata /media/nvrdata   cifs    username=USERNAME,password=PASSWORD,iocharset=utf8,uid=1001,gid=1001,vers=2.0    0   0

Any help is greatly appreciated.
Thank you in advance.

**Comment by Iruberiam** [comment]
I had the same problems, had to change PUID to 99 and PGID to 100
Also from within the container had to chmod -R go+rw /var/cache/zoneminder. Although this may only have been necessary due to the fact I was moving files from an existing zoneminder installation.

**Comment by Wheresitat** [comment]
@Iruberiam thanks for your assistance here, have tried that and get the same issue.
http://prntscr.com/sk18k3 storage is mounted ok, i can write to it manually from inside the container... However, Zoneminder can't create the events, it shows 0bytes in the screenshot.

**Comment by Iruberiam** [comment]
Is the owner of /var/cache/zoneminder/ www-data?

**Comment by Wheresitat** [comment]
From where? From the ubuntu host? or the docker container?
Container:
ls -l /zoneminder
drwxr-xr-x 2 1000 1000 0 May 12 16:02 1
drwxr-xr-x 2 1000 1000 0 May 12 16:02 2
drwxr-xr-x 2 1000 1000 0 May 12 16:02 3
-rwxr-xr-x 1 1000 1000 6 May 12 10:25 test2

Or from ubuntu host
root@bat-docker:/media/nvrdata# ls -l /media/nvrdata/
total 4
drwxr-xr-x 2 higgson higgson 0 May 12 06:02 1
drwxr-xr-x 2 higgson higgson 0 May 12 06:02 2
drwxr-xr-x 2 higgson higgson 0 May 12 06:02 3
-rwxr-xr-x 1 higgson higgson 6 May 12 00:25 test2

**Comment by Iruberiam** [comment]
Well, as I understand it, both. It's an account that exists in both the host and container. It's a change I had to make to my events after copying them over from another machine. Until then I was also getting write permission errors.

**Comment by Wheresitat** [comment]
@Iruberiam thank you very much for the help. Really really appreciate it. I had eventually had to remove the mount point and recreate it i could then change owner to www-data. After that i remounted the volume and it reflected in the container.

**Comment by Iruberiam** [comment]
@Wheresitat , glad to see you've got it working.
