### ISSUE TITLE
tutorial zoneminder zmeventnotification

### ISSUE THREAD

**Issue by nicoxygen** [dlandon/zoneminder#96]
hello i use port 444:443 and 9000:9000 and letsencrypt to openmediavault
my address of zoneminder is https://zm.trucmuch.fr/zm
I can't get zmeventnotification to work even by modifying zmeventnotification.ini and objectconfig.ini, I saw the addresses on the wiki and everything is set up correctly when mounting the docker image.
Could someone help me or tell me or could I find a tutorial with this picture?

**Comment by BluGeni** [comment]
A very in depth guide 
https://zmeventnotification.readthedocs.io/en/latest/guides/install.html
you can skip the install because thats been done for you in this image.
