### ISSUE TITLE
Tag docker images by version.

### ISSUE THREAD

**Issue by Dirbaio** [dlandon/zoneminder#97]
Currently the only tag on Docker Hub is `latest`. This means people have to run `latest`, which has the following problems:

- There's no way to manually pick a fixed version if, say, the latest version has a bug.
- If the machine re-pulls the image (for example, if running on k8s and the node is recreated), it will get a different version than it was running originally, potentially breaking the service without the admin explicitly deciding to do anything.

Ideally there'd be the `latest` tag and one tag per ZoneMinder version.

**Comment by dlandon** [comment]
This docker does not lend itself to Zoneminder versioning.  Every time it restarts, it automatically updates Zoneminder.  This is done so the docker doesn't have to be updated to update Zoneminder.  It also upates the OS to apply any security updates.

**Comment by Dirbaio** [comment]
That's quite unfortunate :( 

As a sysadmin, I'd want to control the exact version I'm running, so I can device when to upgrade, and I can downgrade to the previous version if an upgrade turn out to break the setup.

As this stands right now, the docker can auto-upgrade, break things, and, it's impossible to downgrade.

**Comment by dlandon** [comment]
Yep.  That's the way a lot of people want it to work and I don't have the time to manage versions.  If that doesn't work for you, feel free to find another answer.
